### ISSUE TITLE
Bonding to Struct

### ISSUE THREAD

**Issue by ZENUAV** [SwiftBond/Bond#113]
I have a struct as shown below

```objective-c
/**
 *  RC GPS Data
 */
typedef struct
{
    /**
     *  Gps time
     */
    DJIRCGpsTime mTime;
    /**
     *  Latitude (degree)
     */
    double mLatitude;
    /**
     *  Longitude (degree)
     */
    double mLongitude;
    /**
     *  Speed on X (m/s)
     */
    float mSpeedX;
    /**
     *  Speed on Y (m/s)
     */
    float mSpeedY;
    /**
     *  Current available satellite count
     */
    int mSatelliteCount;
    /**
     *  Accuracy (m)
     */
    float mAccuracy;
    /**
     *  Is Gps data valid
     */
    BOOL mIsValid;
} DJIRCGPSData;
```

I declare a dynamic variable to it as below

```swift
var droneRCGPSData = Dynamic<DJIRCGPSData>(DJIRCGPSData())
```

How can I bond one of the number values to a UILabel.

```swift
droneRCGPSData.value.mTime.mSecond ->> labelAppName
```

The error I'm facing is

```
 Binary operator '->>' cannot be applied to operands of type 'UInt8' and 'UILabel!'
```

Can this be done or do I need to make a duplicate struct with dynamic types and move each item from one struct to the other and bind to the other??

Thanks

Jason

**Comment by srdanrasic** [comment]
Hi Jason,

You need to `map`it, i.e. convert it to String.

```swift
droneRCGPSData.map { data in \"(data.mTime.mSecond)" } ->> labelAppName
```

Hope this helps.

**Comment by ZENUAV** [comment]
Thanks for speedy response.

The compiler does not like the \

Is this correct??

**Comment by srdanrasic** [comment]
Sorry, I misspelled. It corrected now. It's basic Swift string interpolation. 

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/StringsAndCharacters.html#//apple_ref/doc/uid/TP40014097-CH7-ID292
