### ISSUE TITLE
Consider adding dynSelectedSegment to UISegmentedControl

### ISSUE THREAD

**Issue by matoushybl** [SwiftBond/Bond#120]
Could you please add this feature? I think that this is the most valueable output of the view.

**Comment by retsohuang** [comment]
This is what I use in my project https://gist.github.com/b74c473ec9ccd6cbcac1.git

**Comment by retsohuang** [comment]
This is what I use in my project https://gist.github.com/retsohuang/b74c473ec9ccd6cbcac1

**Comment by srdanrasic** [comment]
Will be available in v4.0. You can expect beta release this weekend.
