### ISSUE TITLE
dynamicObservableFor NSNotification should have an argument for a default value

### ISSUE THREAD

**Issue by TadeasKriz** [SwiftBond/Bond#121]
Until the notification is sent, the Dynamic has no value and throws an error when it is bound with fire=true.

**Comment by srdanrasic** [comment]
Right, that's why it's bound with fire=false by the default. It's caused by a bad underlying design. In v4 we will have stateless Observables which will be right fit for this and some other cases like buttons taps, etc.

**Comment by srdanrasic** [comment]
Notification center support has been refactored in v4. Closing.
