### ISSUE TITLE
Bond v4

### ISSUE THREAD

**Issue by srdanrasic** [SwiftBond/Bond#124]
Hi All,

I've just pushed my work on the next major version of Bond to the `bond-4` branch. It's not finished yet, but I'd like to get some feedback while it's still in progress.

Version 4 changes everything from the inside while trying to keep things, at least conceptually, from the outside similar to previous versions.

The major difference is that now everything revolves around base Observable type. Functional aspects are implemented even on a higher lever - on ObservableType protocol. Anything that implements that protocol can be mapped, filtered, observed, reduced, bound, etc.

Dynamic has been renamed to Scalar. It's a stateful Observable whose events are just new values that have been set.

DynamicArray has been renamed to Vector. It's also a stateful Observable, but it's events are operations applied to the Vector (i.e. to the underlying array), like Insert, Delete, Update. No more bunch of will/did* closures. A Vector can perform Batch updates.

The Bond class has been deprecated. Any Observable can now be observed by a simple closure (a sink).

"Unbinding" is now managed by the Disposables, but in most cases it will happen automatically without the need for user intervention.

A new class, the Promise, has been introduced that simplifies asynchronous tasks. It's also an Observable.

As people have been using Bond for FRP, it's now much better supported through the new stateless Observable class that behaves like a hot signal. UIControl events, notifications, etc. are now Observables as they do not store any state.

I'll be writing new Readme in following days which should explain everything much better. In the meantime, if anyone is having some spare time, check out bond-v4 branch.

There are few things that are still in the TODO: filter function for the Vector, KVO, more unit tests.

Regarding the operator `->>`, I'm in favor of replacing it with `|>`.

v4 is written in Swift 2. I'm aiming to have Bond ready and stable before Xcode 7 GM is out, which is I guess in a month.

Thanks!

@tonyarnold @ivanmoskalev @sync @tonyxiao @TadeasKriz

**Comment by tonyarnold** [comment]
Ooooo! 💆🏻

**Comment by ivanmoskalev** [comment]
Awesome :+1:

**Comment by ivanmoskalev** [comment]
@srdanrasic Maybe you can open a pull request to master, so we can discuss things in code comments?

**Comment by srdanrasic** [comment]
@ivanmoskalev Great idea!

**Comment by tonyarnold** [comment]
What's the thinking behind `|>`? I'm no FP expert, but I thought (left associative) bind was `>>=` in more functional languages like Haskell.

**Comment by srdanrasic** [comment]
There is currently a mess with all the different operators in FP frameworks around, so I was thinking that a little bit of consistency would make developers lives easier. I found ReactiveCocoa's operator most pleasing to work with.

On the other hand, you might have a point, they are using that as a pipe operator, so making a distinction might not be a bad idea in this case. 

I don't have a solid decision on the operator yet. All ideas are welcome, including keeping the old one.

**Comment by UPetersen** [comment]
ReactiveCocoa seems to move away from the |> operator with swift 2.0: 

https://github.com/ReactiveCocoa/ReactiveCocoa/pull/2189

**Comment by srdanrasic** [comment]
One possibility is to deprecate custom operator altogether and just use bindTo() method.

**Comment by ivanmoskalev** [comment]
@srdanrasic @UPetersen I used Bond both ways and I can say that the function version looks cleaner. It represents an abstract concept that's instantly understandable even to people who don't know about Bond or haven't read its documentation

**Comment by tonyxiao** [comment]
It feels that we are moving closer to ReactiveCocoa with the bond-4 release. As I understood the initial motivation for Bond (http://five.agency/solving-the-binding-problem-with-swift/) is to have a dead simple implementation of binding for those who don't want the complexity of introducing a reactive paradigm into their programming model. Is that still the case? How do you see us positioning ourselves conceptually?

**Comment by banxi1988** [comment]
I'd prefer not change the operator. cause we have to change more code.

**Comment by tonyarnold** [comment]
I think you should make the operator optional. There will be people who find `bindTo()` more "Swift-like" than the operator. There's no penalty other than documentation to having them both available.

**Comment by srdanrasic** [comment]
@tonyxiao 

Bindings are the priority, it will always stay like that, but bindings are, in their nature, reactive. 

Main improvement in v4 is that Bond now makes clear distinction between two different concepts: Observing (i.e. binding) - vs - State change. 

Observing/Binding in now implemented through the Observable class. It has no state, it just sends events to the registered observables. We needed something like this in order to make observing of things like button taps or notifications correctly, without any hacks.

As for state, we have two classes that can encapsulate it and provide it with the observing/binding capability. They do that by being subclasses of Observable that generate events when encapsulated state changes.

Scalar, the new Dynamic, is even more powerful, yet lighter. It's no longer burdened with memory management, nor with the disposal of Bonds. Bond, a class that had two arrays of back-references to  bound Dynamics for the sake of memory management has been completely deprecated in favour of a plain closure.

Something that I'm very thrilled about is Vector class. It improves upon its predecessor, the DynamicArray, on multiple levels. It no longer requires special kind of a Bond. Changes are delivered as events, sequentially, so it no longer requires various listener closures for different events. It can properly support batch updates and translate those into UICollection/TableView batch change sets.

Those classes are much better now when they are backed by the Observable. Yes, having the Observable allows you to do reactive programming with Bond, but it's by no means a requirement.

**Comment by srdanrasic** [comment]
@banxi1988 @tonyarnold @ivanmoskalev 

I'm currently leaning towards supporting both the `bindTo()` method and the old `->>` operator in a way that the method will be preferred way to go and used in the documentation.

**Comment by tonyarnold** [comment]
:+1: sounds good to me, @srdanrasic!

**Comment by bddckr** [comment]
Great work!
:+1: to the use of the method instead of the operator.
Now that v4 has a proper alpha release, installing via CocoaPods works by pointing at the branch.

The readme currently states "…observing photo downloads with KVO…", but I can't find anything to use KVO with Bond v4. Is it coming later? No hurry, just wondering if I'm missing something. :smile:
I'm asking, because I'm trying to use Bond with Realm. They added full support for KVO for all persisted properties just a few days ago.

**Comment by srdanrasic** [comment]
Thanks @bddckr!

I'm still trying to find the best way to incorporate KVO. I'm currently exploring having Scalars (ex Dynamics) as KVO observers. It would allow you to do something like this with Realm:

```swift
class Dog: Object {
  dynamic var name = ""
  dynamic var birthdate = NSDate(timeIntervalSince1970: 1)
}

extension Dog {
  
  class Observable {
    let name: Scalar<String>
    let birthdate: Scalar<NSDate>
    
    init(dog: Dog) {
      name = Scalar(object: dog, keyPath: "name")
      birthdate = Scalar(object: dog, keyPath: "birthdate")
    }
  }
  
  func observableVariant() -> Dog.Observable {
    return Observable(dog: self)
  }
}

let myDog = Dog().observableVariant()

myDog.name.observe { newName in
  print(newName)
}

realm.write {
  myDog.name.value = "Jim"
}
```

**Comment by bddckr** [comment]
@srdanrasic That looks exactly like what I want. I like the non-magical approach via `observableVariant`. Still waiting for the mentioned fine-grained notifications for Realm, so no rush :smile:

**Comment by frankschlegel** [comment]
Maybe I'm too picky, but I think `Scalar` and `Vector` aren't good names (so was `Dynamic`), because they are way too generic. How about something like `ObservableValue` and `ObservableArray`?

Anyways, thanks for the great framework!

**Comment by tonyarnold** [comment]
Yeah, I think @frankschlegel has a good point. I'd prefer more easily readable/comprehendable names too. FP has a tendency to wander off into academic naming for things, and that discourages people from exploring libraries like RAC, Bond, etc.

**Comment by srdanrasic** [comment]
Those are good points. I'm willing to rename those types.  I'd favor the name that consists of only one word, but the descriptiveness of `ObservableValue` and `ObservableArray` might be a reasonable compromise.

**Comment by ivanmoskalev** [comment]
@srdanrasic @frankschlegel @tonyarnold to my mind `ObservableValue` etc. is too long and verbose.
What about `Bindable` and `BindableArray`? It also plays well with the library name.

**Comment by tonyarnold** [comment]
@ivanmoskalev I quite like the inclusion of "Value" in there. I'd cast my vote for `Observable` before `Binadable`, but I'm easy — both options are better than `Vector`/`Scalar`.

**Comment by srdanrasic** [comment]
Value - Array combination nicely translates to the underlying dimensions - single element vs. the collection of elements - and it also describes statefulness of the type. 

As for the first part, I'm also in favor of Observable because it describes the type better. With Bindable it can be unclear whether that is something that can be bound to or something that binds to something else.

The length I don't like but since this is clearly impossible to make ideal we will have to compromise.

**Comment by frankschlegel** [comment]
That's what we have auto-completion for, right? And normally you only have to use the names once in the declaration of a variable, and not every time you use it. I'm pro descriptive names, even if they are more verbose.

**Comment by ivanmoskalev** [comment]
@frankschlegel this is not about the typing effort. Verbose names in global scope are pain. Verbose type names are pain, because they exist in a global scope. I'm not the only one with [this outlook](https://twitter.com/unclebobmartin/status/360029878126514177). 

> because they are way too generic.

They do serve a generic purpose.

But yes, @srdanrasic and @tonyarnold, I agree, Value-Array postfixes are logical. I too agree that my `Bindable` example is not good, for the reasons stated and because it is verbose as well. 

I'm still convinced that we should think twice before renaming, and try to imagine the actual code.

```(swift)
enum MessageFeedState {
    case Ready
    case Sending
    case Failed
}

class MessageFeedViewModel {
    let title = ObservableValue("")
    let state = ObservableValue<MessageFeedState>(.Ready)
    let messages = ObservableArray([])
}
```

It is definitely much readable than `Vector`/`Scalar`, but it is very verbose. Come on, if something is a variable (or OK, constant), it by definition represents a value in a given point of time. 

Plus, `Observable` in the aforementioned case wraps a _property_ of a class or structure, not the value (which changes). It is `ObservableProperty` then. 

Right, and it is also quite possible that the contained type has reference semantics (plainly put, is a class), and so the instance of `Observable` stores a reference. 

I by no means push my opinion, I just try to highlight the fact that naming is a difficult thing and can't be taken lightly.

**Comment by tonyarnold** [comment]
Naming, cache invalidation and off by one errors, hey? :smile: 

Right, well let's come at this another way — is the `Value`/`Array` postfix necessary? Could things just be declared `Observable` and be done with it? I'm spitballing here.

**Comment by frankschlegel** [comment]
@ivanmoskalev  I actually like your code, but that's a question of taste, I guess.

Also, the `Observable` doesn't wrap the property, it _is_ the property and wraps the property's _value_.

If you don't like `value` because of the ambiguity with the reference semantics, how about `ObservableScalar`?

**Comment by ivanmoskalev** [comment]
@frankschlegel @tonyarnold Really speaking, I'm not that much against the proposed naming to argue over it a lot. I think I conveyed what I thought might be useful for making the final decision, probably better to stop the discussion at that :)

**Comment by frankschlegel** [comment]
@ivanmoskalev Agreed. I wasn't meant to be rude, sorry!

**Comment by ivanmoskalev** [comment]
@frankschlegel Hey, it was me arguing the most :)

**Comment by srdanrasic** [comment]
I'm glad we're having this discussion. As @ivanmoskalev, this should not be taken lightly.

I like that spitball, @tonyarnold, but I'll have to see if it is possible. There already exists class Observable that does not hold state. Scalar and Vectors are like stateful Observables. Stateless Observable is used for things like buttons taps.

**Comment by bddckr** [comment]
@tonyarnold @srdanrasic That would provide very concise variables:
```swift
class MessageFeedViewModel {
  enum State {
    case Ready
    case Sending
    case Failed
  }
  
  let title = Observable("")
  let state = Observable(State.Ready)
  let messages = Observable([Message]())
}
```
I can see the distinction between stateful and stateless observables useful for implementing Bond, but have API consumers any interest in the distinction? Observing button taps vs changes to a string are in the end just observations.

**Comment by srdanrasic** [comment]
I can easily make this work for scalar values. Arrays are bit trickier, not sure if it is even possible. Problem is that the array Observable does not send events of an Array<T> type, but of an ArrayEvent<T> type that describes the change that just happened, like .Insert(element: T, atIndex: Int).

Supporting 

```swift
let title = Observable("")
let state = Observable(State.Ready)
```

is not a problem, but supporting 

```swift
let messages = Observable([Message]())
```

is a problem because the actual type has to be

 ```swift
let messages: Observable<ArrayEvent<Message>>
```

And there does not seem to be a way to infer that just from the initializer. We would would always have to be explicit like

```swift
let messages = Observable(ArrayEvent([Message]()))
```

or 

```swift
let messages = Observable<ArrayEvent<Message>>([])
```

Swift Extensions are just not that powerful yet it would seem.

I'm still not giving up, though, there might be a workaround through the protocols.

**Comment by srdanrasic** [comment]
I've experimented with this for a while now and it does not seem possible to make Swift infer types in the fashion I mentioned in the previous post.

Therefore, I'm leaning towards using Observable and ObservableArray. I think those are the simplest and most understandable names to the majority of people.

```swift
enum MessageFeedState {
    case Ready
    case Sending
    case Failed
}

class MessageFeedViewModel {
    let title = Observable("")
    let state = Observable(MessageFeedState.Ready)
    let messages = ObservableArray([Message]())
}
```

**Comment by ivanmoskalev** [comment]
@srdanrasic I'm for this decision.

**Comment by srdanrasic** [comment]
@ivanmoskalev, great, I've just pushed it as v4.0.0-alpha.2 :)

**Comment by zdenektopic** [comment]
Hi. I was thinking. What about instead of textField.bnd_text to have something like textField.bind().text.bindTo(something) or next {} etc...

**Comment by bddckr** [comment]
@srdanrasic I have a use case to use the KVO part differently than currently possible.

I have some key paths to observe that result in different `EventType`s. Because of the lifecycle management I have to store the `Observables` somewhere.
```swift
var observables: [ObservableType] // error: protocol 'ObservableType' can only be used as a generic constraint because it has Self or associated type requirements
```
```swift
var observables: [Observable<EventType>] // won't work: I observe multiple `EventType`s
```
To solve this I'd just do
```swift
var disposables: [DisposableType]
```
but this won't retain the observed `Observable`s, effectively observing nothing.

-

Ideally I'd be able to do
```swift
let theObject: ObservedObject = …
let observable = Observable(object: theObject, keyPaths: ["name", "balance"])
let disposable = observable.observe { (object, keyPath, changes) in
	// theObject === object
	// theObject.name or theObject.balance did change, check keyPath for which
	// changes is the KVO change array of type [String: AnyObject]
}
disposables.append(disposable) // no need to store observable
```
To improve the KVO API to include every use case, I suggest something like this:
```swift
public extension Observable {
	typealias KeyValueChanges = [String: AnyObject]
	// ideally these class funds would be convenience initializers…
	
	/// Creates a new Observable<(T, String, KeyValueChanges)> that observes the specified key paths on object
	/// (observed object, changed keyPath, kvo change array)
	public class func observeKeyPaths<T: NSObject>(object: T, keyPaths: [String], options: NSKeyValueObservingOptions = .New) -> Observable<(T, String, KeyValueChanges)> {
		// …
		let tuple = (object, "", KeyValueChanges())
		return Observable<(T, String, KeyValueChanges)>(tuple) // don't send anything to potential observers, NSKeyValueObservingOptions.Initial will handle this
	}
	
	public class func observeKeyPath<T: NSObject>(object: T, keyPath: String, options: NSKeyValueObservingOptions = .New) -> Observable<(T, KeyValueChanges)> {
		// …
		let tuple = (object, KeyValueChanges())
		return Observable<(T, KeyValueChanges)>(tuple) // don't send anything to potential observers, NSKeyValueObservingOptions.Initial will handle this
	}
}
```
I don't know if `object` can be stored strongly on the returned `Observable` (or the used `KVOHelper` object). The docs say ["Neither the receiver, nor anObserver, are retained."](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Protocols/NSKeyValueObserving_Protocol/index.html#//apple_ref/occ/instm/NSObject/addObserver:forKeyPath:options:context:)
One could argue that `T` in the `EventType` tuple is not needed. But I think this would enable the caller to reuse observing closures (at least when the type is the same).

With this one could leverage all the KVO functionality. Let me know what you think.

**Comment by srdanrasic** [comment]
Hi @bddckr, I'm not sure that I understand why you prefer coalescing observation of different key paths into one observable and then doing `if` on the event over having one observable per key path. If retention is the only problem, you could save them into an array of [AnyObject] type, bud ideally you would have a property for each observable. 

Yes, Observable will strongly reference the target object through KVOHelper. 

Having a disposable manage lifecycle of the observable is an interesting idea I'll play with.

**Comment by bddckr** [comment]
@srdanrasic `combineLatest` on multiple KVO observables helps with my use case a lot… I guess you can forget everything I wrote. :sweat_smile: Thanks for listening, though!

**Comment by nayzak** [comment]
Just off top. When I tried to implement MVVM pattern in my projects I began to develop own library that behaves like Bond v4, but it was far away from Swift 2.0. I gave up because Bond become nice multipurpose library (over engineered for my taste). And now it seems to be great tool for that purposes it been thought for. Great work! Thank you.

**Comment by srdanrasic** [comment]
Glad to hear that, thank you. Yeah, Swift 2.0 made current version much simpler that it would otherwise be....

**Comment by joshavant** [comment]
For anyone who stumbles on this page from searching around the Bond GitHub project, it seems like some of info in the original post in this thread is out of date. Consult the official documentation/source for the latest info!

**Comment by joshavant** [comment]
@srdanrasic The breaking changes from v4 to v3 have been a particularly large and difficult set of changes. That leads me to ask... What are your plans for the future of Bond?

How often will there be breaking changes like the v4 -> v3 transition?

Hopefully the (final) stability of Swift 2.0 means the stability of the Bond API? :)

**Comment by srdanrasic** [comment]
Good question @joshavant. No, there are no breaking changes in sight and all future updates should be just extensions that introduce new capabilities without changing existing APIs.
