### ISSUE TITLE
How can I get collection view cell from UICollectionViewDataSourceBond?

### ISSUE THREAD

**Issue by retsohuang** [SwiftBond/Bond#128]
I try to retrieval collection view cell form `collectionView.cellForItemAtIndexPath(indexPath)` and it always return nil.

**Comment by srdanrasic** [comment]
Hmm, are you sure this is related to Bond. Is your cell visible? Is index path good?

>Return Value
>The cell object at the corresponding index path or nil if the cell is not visible or indexPath is out of range.

**Comment by retsohuang** [comment]
My bad :(
