### ISSUE TITLE
Swift bond disables action connector for uibutton

### ISSUE THREAD

**Issue by juhaelee** [SwiftBond/Bond#13]
when you try to hook up an action using storyboard after installing swiftbond, unbuttons can't create an ibaction using control+click+drag

**Comment by srdanrasic** [comment]
Can't or can but it doesn't work afterwards?

**Comment by juhaelee** [comment]
The option of "action" doesn't even appear anymore

On Wednesday, February 11, 2015, Srđan Rašić <notifications@github.com>
wrote:

> Can't or can but it doesn't work afterwards?
>
> > On 11 Feb 2015, at 18:31, juhaelee <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > when you try to hook up an action using storyboard after installing
> swiftbond, unbuttons can't create an ibaction using control+click+drag
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SwiftBond/Bond/issues/13#issuecomment-73926195>.
>


-- 
Ju Hae Lee

**Comment by srdanrasic** [comment]
Hmm, I don't see how this could be connected to Swift Bond. You should try reproducing it in a new project... If it doesn't work send me that new project and I'll investigate.

**Comment by srdanrasic** [comment]
Ok juhaelee, I was able to reproduce this. You don't need to send me anything.

**Comment by srdanrasic** [comment]
This looks like a bug in Xcode. If you extend UIKit object, it looses action/event options in Interface builder. Even following is enough to break Interface Builder

```swift
protocol SomeProtocol {
}

extension UISlider: SomeProtocol {
}
```

Crazy. I'll see what can be done...

**Comment by srdanrasic** [comment]
Filed a bug at Apple Bug Reporter: 19799266.

**Comment by srdanrasic** [comment]
juhaelee, you can use Bond to handle the action, for example:

```swift
var buttonEventBond: Bond<UIControlEvents>?
...
self.buttonEventBond = button.filter { $0 == UIControlEvents.TouchUpInside } ->> { event in
  login()
}
```
Make sure you retain the bond like in the snippet above.

**Comment by juhaelee** [comment]
I get the error "UIButton" does not have a member named 'filter'. Does it need to be a Dynamic<UIButton> ?

**Comment by srdanrasic** [comment]
Fixed my answer.

**Comment by juhaelee** [comment]
Thank @srdanrasic, I have another question if you the time:

I have a ViewModel called ItemViewModel, a UITableViewCell called ItemTableViewCell and a view Controller called ItemViewController.

In my ItemsViewController I store a private variable called Items which I load in viewDidLoad(). And to get my tableview running I have the following cellForAtIndexPath function:

```
func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCellWithIdentifier(itemCellIdentifier) as ItemTableViewCell

        let item: ItemViewModel = items[indexPath.row]
        cell.viewModel = item
        
        return cell
    }
```

Trying to do the MVVM pattern, in my ItemTableViewCell I have the following code:
```
class StoreTableViewCell: UITableViewCell {

    @IBOutlet weak var itemImage: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var addButton: UIButton!
    
    var viewModel: StoreViewModel! {
        didSet {
            itemImage.image = viewModel.image
            nameLabel.text = viewModel.name
            addButton.imageView?.image = viewModel.addImage
            viewModel.favorite ->> Bond<Bool>() { [unowned self] value in
                println("The value changed")
                self.nameLabel = "I changed"
            }
        }
    }
}
```

What I'm trying to do here is that every time a cell is replaced with a new Item, it creates a Bond for the viewModel's property 'favorite', so that whenever favorite is changed, I can change something in the view of the ItemTableViewCell

However, when I try to test it out using didSelectRowAtIndexPath:
```
    func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        let item: ItemViewModel = items[indexPath.row]
        println("\(item.name) : \(item.favorite.value)")
        item.favorite.value = true
    }
```

It does NOT execute the Bond. Can you tell me what I'm doing wrong here?

Here is the ViewModel if it helps:
```
class ItemViewModel {
    
    let name: String
    let image: UIImage
    var addImage: UIImage
    var favorite: Dynamic<Bool>
    
    init(_ rlmItem: Item){
        store = rlmItem
        
        name = rlmItem.name
        image = UIImage(data: rlmItem.image!)!
        followImage = UIImage(named: "favorite")!
        favorite = Dynamic(false)

    }
}
```

**Comment by srdanrasic** [comment]
You need to retain (strongly reference) the bond like this

```swift
class StoreTableViewCell: UITableViewCell {
  
  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!
  
  var favoriteBond: Bond<Bool>?
  
  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name
      addButton.imageView?.image = viewModel.addImage
      favoriteBond = viewModel.favorite ->> { [unowned self] value in
        println("The value changed")
        self.nameLabel = "I changed"
      }
    }
  }
}
```

I should emphasise this in readme I guess :)

**Comment by juhaelee** [comment]
Awesome that worked!!! Say if I wanted to put another bond that responded to that first bond though. I changed addImage in my model to be Dynamic\<UIImage?\> and changed my  tableviewcell to:
```swift
class ItemTableViewCell: UITableViewCell {

  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!

  var favoriteBond: Bond<Bool>?
  // add a new UIImage bond
  var addImageBond: Bond<UIImage?>?

  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name
      // create a new bond that has the button's image view watching for changes in the viewMode's addImage(:UIImage) 
      addImageBond = viewModel.addImage ->> addButton.imageView!
      favoriteBond = viewModel.favorite ->> { [unowned self] value in
        println("The value changed")
        self.nameLabel = "I changed"
      }
    }
  }
}
```

However I get this error that says **'UIImageView' is not convertible to 'Bond<UIImage?>'**

**Comment by srdanrasic** [comment]
Each UIKit object (button, label, imageview...) provides a Bond in a `designatedBond` property that you can use instead of creating and retaining your own bonds.

When types mismatch, for example `favorite`is Bool, but you want it to update label whose designatedBond needs String, you can use map() to transform type.

```swift
class ItemTableViewCell: UITableViewCell {
  
  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!
  
  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name
      viewModel.addImage ->> addButton.imageView!.designatedBond
      viewModel.favorite.map { newValue in
        return newValue ? "favorited" : "not favorited"
      } ->> self.nameLabel.designatedBond
    }
  }
}
```

As designatedBond is defined by a protocol, following should also work:

```swift
class ItemTableViewCell: UITableViewCell {
  
  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!
  
  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name
      viewModel.addImage ->> addButton.imageView!
      viewModel.favorite.map { newValue in
        return newValue ? "favorited" : "not favorited"
      } ->> self.nameLabel
    }
  }
}
```

**Comment by juhaelee** [comment]
How come I can't retain the **viewMode.addImage ->> addButton.imageView!** bond in a variable like: 
```swift
var addImageBond: Bond<UIImage?>?
```

so that I can store it in didSet within ItemTableViewCell like so:
```swift
didSet {
   addImageBond = viewModel.addImage ->> addButton.imageView!
}
```

I'm getting the error: **'UIImageView' is not convertible to 'Bond<UIImage?>'**

**Comment by srdanrasic** [comment]
Checkout the definition of ->> operator:

```swift
public func ->> <T>(left: Dynamic<T>, right: T -> Void) -> Bond<T>
public func ->> <T: Dynamical, U where T.DynamicType == U>(left: T, right: Bond<U>)
public func ->> <T: Dynamical, U: Bondable where T.DynamicType == U.BondType>(left: T, right: U)
public func ->> <T, U: Bondable where U.BondType == T>(left: Dynamic<T>, right: U)
```

It will return a Bond only when there is a closure on the right side because in that case a new Bond is created. In all other cases you already have a Bond on right side so there is no need to return anything.

In case of any UIKit object, Bond on the right side is the one saved into `designatedBond` property.

**Comment by srdanrasic** [comment]
Checkout demo app, it shows very similar use case to yours: https://github.com/SwiftBond/Bond-Demo-App

**Comment by juhaelee** [comment]
Sorry about all the questions. And thank you so much for answering them. I'm still confused though. I thought I needed to store a strongly referenced variable to the ItemTableViewCell

```swift
class ItemTableViewCell: UITableViewCell {

    @IBOutlet weak var itemImage: UIImageView!
    @IBOutlet weak var nameLabel: UILabel!
    @IBOutlet weak var addButton: UIButton!
    var favoriteBond: Bond<Bool>?

    var viewModel: ItemViewModel! {
        didSet {
            itemImage.image = viewModel.image
            nameLabel.text = viewModel.name
            addButton.imageView?.image = viewModel.addImage
            favoriteBond = viewModel.favorite ->> { [unowned self] value in
               println("The value changed")
               self.nameLabel = "I changed"
            }
        }
    }
}
```

This makes sense to me now. However, what if I wanted to do this:
When the Model view's property favorite is change, I want to change the modelView's addImage image

so in the favoriteBond, can I do this?:
```swift
 favoriteBond = viewModel.favorite ->> { [unowned self] value in
               viewModel.addImage.value = UIImage(named: 'newImage')
}
```

But I also want the ItemTableViewCell to watch and change the itemImage(:UIImageView) when the viewModel's addImage  changes. So I would typically use:

```swift
viewModel.addImage ->> addButton.imageView!
```

Right? But this doesn't happen when I change the viewModel's favorite property because it doesn't have a strong reference within the ItemTableViewCell

So currently I have this code:
```swift
class ItemTableViewCell: UITableViewCell {

  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!

  var favoriteBond: Bond<Bool>?

  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name
      // create a new bond that has the button's image view watching for changes in the viewMode's addImage(:UIImage) 
      viewModel.addImage ->> addButton.imageView!
      favoriteBond = viewModel.favorite ->> { [unowned self] value in
        println("The value changed")
        viewModel.addImage.value = UIImage(named: 'newImage')
      }
    }
  }
}
```

So my question is, how do I create a strong reference to the **viewModel.addImage ->> addButton.imageView!** bond so that whenever the viewModel's favorite property changes, it automatically updates the UIButton in the ItemTableViewCell?

**Comment by srdanrasic** [comment]
Expression `dynamic ->> closure` creates a Bond, so you need to strongly reference it.

Expression `dynamic ->> bond` does not create any Bond because you already have a Bond that you're binding to (the thing on the right side).

Expression `dynamic ->> someUiKitObject` is equivalent to `dynamic ->> bond` because under the hood it actually performs `dynamic ->> someUiKitObject.designatedBond`. So, Bond object already exists, you're only establishing a connection to it.


Your problem might be that you're not setting button's image correctly. You should use `setImage:forState:` method when setting an image of UIButton. For that you need a custom bond with closure.

```swift
class ItemTableViewCell: UITableViewCell {
  
  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!
  
  var favoriteBond: Bond<Bool>?
  var addImageBond: Bond<UIImage?>?
  
  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name

      addImageBond = viewModel.addImage ->> { [unowned self] image in
        self.addButton.setImage(image, forState: UIControlState.Normal)
      }
      
      favoriteBond = viewModel.favorite ->> { [unowned self] value in
        println("The value changed")
        viewModel.addImage.value = UIImage(named: 'newImage')
      }
    }
  }
}
```

You're welcome. Your questions tell me where I should improve documentation.

**Comment by srdanrasic** [comment]
juhaelee, I updated readme and release v2.2.0 with additional Bonds. Not you should be able to update your button image like this:

```swift
class ItemTableViewCell: UITableViewCell {
  
  @IBOutlet weak var itemImage: UIImageView!
  @IBOutlet weak var nameLabel: UILabel!
  @IBOutlet weak var addButton: UIButton!
  
  var favoriteBond: Bond<Bool>?
  
  var viewModel: StoreViewModel! {
    didSet {
      itemImage.image = viewModel.image
      nameLabel.text = viewModel.name
      
      viewModel.addImage ->> addButton.imageForNormalStateBond
      
      favoriteBond = viewModel.favorite ->> { [unowned self] value in
        println("The value changed")
        viewModel.addImage.value = UIImage(named: 'newImage')
      }
    }
  }
}
```

**Comment by juhaelee** [comment]
@srdanrasic Beautiful. Thank you so much, the documentation is also much better now! Awesome update

**Comment by srdanrasic** [comment]
Action connector bug in Interface Builder handled in v2.2.1.

**Comment by DenHeadless** [comment]
@srdanrasic Hey! What's status on this bug? This is happening in my project with ReactiveKit and ReactiveUIKit. I first noticed this on UISegmentedControl, all actions are gone, unless UISegmentedControl extension is commented out.
