### ISSUE TITLE
->> not supporting UIImage and UIImageView

### ISSUE THREAD

**Issue by gvimlan95** [SwiftBond/Bond#130]
![screen shot 2015-08-20 at 8 02 58 pm](https://cloud.githubusercontent.com/assets/9544447/9382828/9d21281a-4776-11e5-8006-c444a0132eff.png)

**Comment by ushisantoasobu** [comment]
@gvimlan95 

You should use `dynImage`, below is an example.

```swift
var image = Dynamic<UIImage?>(UIImage(named: "some_icon"))
image ->> someImageView.dynImage
```

**Comment by gvimlan95** [comment]
@ushisantoasobu  Hey man, Thanks for the reply. But sadly I m facing the same error even after changing. 
![screen shot 2015-08-20 at 10 49 15 pm](https://cloud.githubusercontent.com/assets/9544447/9386371/c81f90b2-478d-11e5-9c05-40b21b95457c.png)

**Comment by srdanrasic** [comment]
Are you using Bond 4? Some things have been renamed. Check out Readme can that be found here: https://github.com/SwiftBond/Bond/tree/bond-4. Readme is not yet finished, though, but migration section might be useful.

**Comment by gvimlan95** [comment]
@srdanrasic 
Hey man. Thank you for the reply. I looked up at the migration document earlier and it was advised to "bindTo" instead of "-->". However, I still had the same problem. 
![screen shot 2015-08-20 at 11 07 22 pm](https://cloud.githubusercontent.com/assets/9544447/9386906/5cf30e1a-4790-11e5-86ed-11517979fb57.png)

**Comment by srdanrasic** [comment]
You need to bindTo(imageView.bnd_image) because designated dynamics are deprecated.

**Comment by gvimlan95** [comment]
@srdanrasic 
Its working :)

Thank you my friend. And your doing a great job with the framework.

**Comment by srdanrasic** [comment]
Thank you!
