### ISSUE TITLE
observable var error comparing to nil

### ISSUE THREAD

**Issue by gvimlan95** [SwiftBond/Bond#134]
Hey

I have a observable var call "data"
Below is my function:

if let data = data.value{
            print("Data value \\(data.value)")
            return
        } 

I only want this to run when there is data stored in the "data" variable. But at this point the variable is empty but still it runs this function. Is it Swift error or the swift Bond error?

Sorry for this noob question. Really grateful if you could help.
Thank you

**Comment by srdanrasic** [comment]
Hi @gvimlan95, how is your `data` define and how do you set it?

**Comment by gvimlan95** [comment]
@srdanrasic Below is my full function:

var data = Dynamic<[PFUser]?>(nil)

if let data = data.value{
print("Data value \(data.value)")
return
}

**Comment by srdanrasic** [comment]
Hmm, this is probably due the fact that a Dynamic internally saves the value as an Optional. So the property `value` is actually of the type [PFUser]??. And it has value: Optional.None. Can you try:

```swift
if let data = data.value! {
  print("Data value (data.value)")
}
```

**Comment by gvimlan95** [comment]
Its working man. Thank you :)
