### ISSUE TITLE
textFieldDidBeginEditing delegate

### ISSUE THREAD

**Issue by zhouhao27** [SwiftBond/Bond#139]
I'm wondering if there is a way to support textFieldDidBeginEditing delegate event in Bond? (I'm working on a Swift 2.0 project).

Thanks.

**Comment by srdanrasic** [comment]
Well, not directly, but you could register a notification handler with Bond for UITextFieldTextDidBeginEditingNotification notification:

```swift
NSNotificationCenter.defaultCenter().bnd_notification(UITextFieldTextDidBeginEditingNotification, object: self.textField).observe { notification in
  // your action
}.disposeIn(self.bnd_bag)
```

Make sure you unregister (dispose) the handler when your text field is destroyed. If you are doing this from a view or view controller, the easiest way is to dispose it in the dispose bag attached to view/view controller. bnd_bag is provided as an extension to NSObject and all of its subclasses.
