### ISSUE TITLE
Filter doesn't work for a customised UIControl

### ISSUE THREAD

**Issue by zhouhao27** [SwiftBond/Bond#141]
I have a customized UIControl. It seems the filter doesn't work for me. Here is the source code:

      myControl.bnd_controlEvent
            .filter { $0 == UIControlEvents.TouchUpInside }
            .observe {
                [unowned self] e in
                print("Here")
        }

The print is never called although I did get the TouchUpInside event in my code for the UIControl. My code:

    func setup() {        
        self.addTarget(self, action: "onTouchUpInside:", forControlEvents: UIControlEvents.TouchUpInside);
    }
    
    func onTouchUpInside(sender: UIControl) {
        isChecked = !isChecked
        delegate?.didSelectCheckbox(self)
    }

What could be wrong in my code? Thanks

**Comment by srdanrasic** [comment]
Hmm, I was not able to reproduce your issue. How is your UIControl implemented? Does it even send UIControlEvents.TouchUpInside events?

**Comment by zhouhao27** [comment]
Inside the customised UIControl I got the TouchUpInside event. Should I do something in that event handler?

My code in my UIControl:

    // MARK: local functions
    func setup() {      
        self.addTarget(self, action: "onTouchUpInside:", forControlEvents: UIControlEvents.TouchUpInside);
    }

    func onTouchUpInside(sender: UIControl) {
        isChecked = !isChecked
        delegate?.didSelectCheckbox(self)
    }

**Comment by retsohuang** [comment]
You miss the sendActionsForControlEvents(.TouchUpInside)
