### ISSUE TITLE
beginBatchUpdates/endBatchUpdates?

### ISSUE THREAD

**Issue by adly-holler** [SwiftBond/Bond#142]
On iOS, `NSFetchedResultsController` vends a 2-dimensional array of Core Data objects, and it reports changes by calling
```
controllerWillChangeContent
controller(didChangeObject:)
controller(didChangeObject:)
controller(didChangeSection:)
controller(didChangeObject:)
…
controllerDidChangeContent
```

It would be convenient to be able to create an `ObservableArray` using an `NSFetchedResultsController`. I could buffer the changes myself, but it'd be more convenient if Bond allowed me to translate those FRC calls into ObserveableArray calls 1:1 i.e.

```
beginBatchUpdate
insert
replace
insert
delete
…
endBatchUpdate
```

**Comment by srdanrasic** [comment]
Hi @adly-holler,

Sorry for not responding earlier, I was on vacation. So, you'd prefer `beginBatchUpdates/endBatchUpdates` methods over `performBatchUpdates` closure? It would be a compromise of robustness for flexibly/convenience. Might be reasonable in this case. Give me a day to rethink.

**Comment by srdanrasic** [comment]
Hi @adly-holler,

I think we should keep performBatchUpdates method. Doing begin/end reduces robustness too much. 

What you can do easily is create ObservableArrayOperation.Batch operation that contains all operations that you calculated from FRC.

```swift
// on FRC willChange:
var operations: [ObservableArrayOperation<Int>] = []

// for each FRC call:
operations.append(.Insert([1, 2], fromIndex: 0))
...

// on FRC didChange:
let batchOperation = ObservableArrayOperation.Batch(operations: operations)
array.applyOperation(batchOperation)
```

Hope this helps

**Comment by adly-holler** [comment]
Yeah but unfortunately by the time I apply the operation, my FRC's data has already changed so if any of the changes cause someone else to look at the FRC, they'll be expecting to see an older version of the data than they'll get. 

No big deal though, and no great way around it.
