### ISSUE TITLE
v4 can't install with Carthage

### ISSUE THREAD

**Issue by entotsu** [SwiftBond/Bond#144]
Cartfile:
> github "SwiftBond/Bond" ~> 4.0.0

Many Error was Occurred :cry: 

> The following build commands failed:
	CompileSwift normal x86_64 /Users/Takuya/Desktop/bondDemo/Carthage/Checkouts/Bond/Bond/Core/Observable.swift
	CompileSwift normal x86_64 /Users/Takuya/Desktop/bondDemo/Carthage/Checkouts/Bond/Bond/Extensions/iOS/UILabel+Bond.swift
	CompileSwift normal x86_64 /Users/Takuya/Desktop/bondDemo/Carthage/Checkouts/Bond/Bond/Core/OptionalType.swift
	CompileSwift normal x86_64 /Users/Takuya/Desktop/bondDemo/Carthage/Checkouts/Bond/Bond/Extensions/iOS/UIRefreshControl+Bond.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(5 failures)

**Comment by tonyarnold** [comment]
Why did you close this? Did you get it working?

**Comment by entotsu** [comment]
Sorry, I didn't use Swift2.0.

**Comment by tonyarnold** [comment]
Righto — yep, that would do it! :+1:

**Comment by entotsu** [comment]
I download Xcode7-beta.
I made empty project and install "v4" with Carthage again.
But, It still can't install. :sob: 

Same Error is Occurred.
A lot of amount errors like below.

> Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd1d619aac0>{number = 8, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
2015-09-08 14:25:20.606 xcodebuild[82300:1779869]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/SpecificationTypes/BuiltInSpecifications/Compilers/XCGccMakefileDependencies.m:77
Details:  Failed to load dependencies output contents from ``/Users/Takuya/Library/Developer/Xcode/DerivedData/Bond-fqgmogkbouyvqebifdubujldystv/Build/Intermediates/Bond.build/Release-iphonesimulator/Bond.build/Objects-normal/x86_64/UIView+Bond.d''. Error: Error Domain=NSCocoaErrorDomain Code=260 "The file “UIView+Bond.d” couldn’t be opened because there is no such file." UserInfo=0x7fd1d64019d0 {NSFilePath=/Users/Takuya/Library/Developer/Xcode/DerivedData/Bond-fqgmogkbouyvqebifdubujldystv/Build/Intermediates/Bond.build/Release-iphonesimulator/Bond.build/Objects-normal/x86_64/UIView+Bond.d, NSUnderlyingError=0x7fd1d6448960 "The operation couldn’t be completed. No such file or directory"}. User info: {
    NSFilePath = "/Users/Takuya/Library/Developer/Xcode/DerivedData/Bond-fqgmogkbouyvqebifdubujldystv/Build/Intermediates/Bond.build/Release-iphonesimulator/Bond.build/Objects-normal/x86_64/UIView+Bond.d";
    NSUnderlyingError = "Error Domain=NSPOSIXErrorDomain Code=2 \"The operation couldn\U2019t be completed. No such file or directory\"";
}.
Function: void XCGccMakefileDependenciesParsePathsFromRuleFile(NSString *__strong, void (^__strong)(NSString *__strong))
Thread:   <NSThread: 0x7fd1d619aac0>{number = 8, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **
