### ISSUE TITLE
Can't install v4 with CocoaPods

### ISSUE THREAD

**Issue by entotsu** [SwiftBond/Bond#145]
I used Xcode7-beta :smiley_cat:

**Comment by entotsu** [comment]
Finally I install v4 from GitSubmodule.

**Comment by yoshinorisano** [comment]
@entotsu 
I've successfully installed 4.0.0-beta3, which is the latest version, using CocoaPods.
My Podfile is like this:
```
use_frameworks!
pod 'Bond', '4.0.0-beta3
```

The README.md states that we should add ``` pod 'Bond', '~> 4.0'  ``` to Podfile, but this does not work for now.

**Comment by srdanrasic** [comment]
This should work now when we are out of beta.
