### ISSUE TITLE
SimpleDisposable ?

### ISSUE THREAD

**Issue by serieuxchat** [SwiftBond/Bond#147]
I am getting an error that SimpleDisposable cannot be constructed because it does NOT have an initializer. Is it meant to be used outside of Bond itself?

Kind regards,
Sergey

**Comment by srdanrasic** [comment]
Thanks for reporting this, We'll make it public.

**Comment by serieuxchat** [comment]
Thanks a lot!

There is a small question I have: I am trying to write a function which would return an EventProducer for a network operation (to retrieve a certain kind of value). However, there seems to be no built-in way to have such operation to fire (i.e. to trigger it). I was looking at an example of NSNotificationCenter+Bond, but there the firing of a notification is done by NSNotificationCenter itself.

**Comment by ivanmoskalev** [comment]
@serieuxchat I think what you are talking about is futures and promises. I think those were featured in the first alpha of v4 but removed later.

Have a look at [BrightFutures](https://github.com/Thomvis/BrightFutures). You can subscribe to the result of a Future and manipulate your Observables imperatively from there (using `someObservable.next(value)`)
