### ISSUE TITLE
Clone a DynamicArray value

### ISSUE THREAD

**Issue by pasviegas** [SwiftBond/Bond#16]
It would be nice if you could clone a dynamic value, the clone would still change if the elements on the original one changes and vice-versa but new values on the clone wouldn't affect the original.

My use case is: I have a tableview and a DynamicArray<Project> and I would like the first row to be a default value but without changing the my DynamicArray<Project>

```swift
        let projects: DynamicArray<Project> = userViewModel.projects

        projects.clone().insert(DefaultProject(), atIndex: 0).map { [unowned self] (project: Project) -> ProjectCellView in
            let cell = self.tableView.dequeueReusableCellWithIdentifier("cell") as ProjectCellView
            project.viewModel().name ->> cell.nameLabel
            return cell
        } ->> self.tableView
``` 

I would be happy with any other suggestion too :)

Thanks

**Comment by srdanrasic** [comment]
Interesting scenario. Unfortunately, I don't see a "Bond way" of solving this at the moment. You can always manually implement data source and use ArrayBond to do table view updates like here: https://github.com/SwiftBond/Bond/blob/master/Bond/Bond%2BUIKit.swift#L589-L627

But you have valid scenario and we need to make it work :) I'll keep you informed.

**Comment by srdanrasic** [comment]
Hi Pedro,

Bond v3 supports multiple sections so you can have first row as additional section. Check out updated README.
