### ISSUE TITLE
KVO Optional support problem with optional types

### ISSUE THREAD

**Issue by killev** [SwiftBond/Bond#164]
Hello guys,
You have a small mistake in code that serves Optional KVO
Insted of:

if !updatingFromSelf {
        observer.set(value as? AnyObject)
}

there must be:

 if !updatingFromSelf {
        observer.set(value.value as? AnyObject)
 }
Otherwise it incorrectly assings new value.

Regards!
Peter

**Comment by srdanrasic** [comment]
You're probably right. Thanks will fix it.

**Comment by kevin-hirsch** [comment]
Hey @srdanrasic, is there any updates on this issue? :)

**Comment by srdanrasic** [comment]
Fixed in v4.0.1.
