### ISSUE TITLE
v3 -> v4 String + Array reduce conversion

### ISSUE THREAD

**Issue by joshavant** [SwiftBond/Bond#167]
I have a part of my app where the user can type a string into a 'filter'-type textfield and it will filter down a tableview of contact entries. I had a working implementation in Bond v3, however I'm not sure of the correct style or approach for v4.

Here was the working Bond v3 implementation:
```
var filter = Dynamic<String?>("")
var allPeople = DynamicArray<ContactViewModel>([])
var filteredPeople = DynamicArray<ContactViewModel>([])

reduce(filter, allPeople) {
    filterString, people in
    if let query = filterString where query != "" {
        return people.filter {
          contact in
          // doing other stuff
        }
    } else {
        return people
    }
} ->> filteredPeople
```

Using the Bond v4 release notes and examples, I've come up with this for a v4 re-implementation, but am getting a weird compiler error:
```
var filter = Observable<String?>("")
var allPeople = ObservableArray<ContactViewModel>([])
var filteredPeople = ObservableArray<ContactViewModel>([])

combineLatest(filter, allPeople).map({
    (observables: (filterString: String?, peopleArrayEvent: ObservableArrayEvent<[ContactViewModel]>)) -> [ContactViewModel] in
    return observables.peopleArrayEvent.sequence
}).bindTo(filteredPeople)
```

However, that does not compile, and I get the compiler error:
`Cannot invoke 'bindTo' with an argument list of type '(ObservableArray<ContactViewModel>)'`.

(ignore the fact that I'm just returning `sequence`... just trying to get a basic prototype of this working, at this point)

This compiler error seems weird because, of course, that type should be bindable... I'm not really sure what's going on here.

So, I'm submitting this issue:
a.) As a request for help on how to do this :)
b.) As commentary on whether or not it seems like the right syntax/design to be passing around `ObservableArrayEvent`s, in this use case... because to me, this is bit of a hard-to-understand syntax. (But, it's totally possible I'm going about this wrong and maybe there's a better approach...)

Thank you for the insight!

**Comment by srdanrasic** [comment]
You probably want to do something like this:

```swift
  var filter = Observable<String?>("")
  var allPeople = ObservableArray<ContactViewModel>([])
  var filteredPeople = ObservableArray<ContactViewModel>([])
  
  filter
    .throttle(0.5, queue: Queue.Main)
    .observe { term in
      filteredPeople.array = allPeople.filter { contactViewModel in
        return /* filter logic */
      }
  }
```

You can remove throttle if you want to perform search for every letter user types, but it is usually a good trick to optimise CPU/network usage.

**Comment by joshavant** [comment]
Thank you so much for the pointers, Srđan! That worked great!
