### ISSUE TITLE
Problem with bridged Objective-C enums

### ISSUE THREAD

**Issue by serieuxchat** [SwiftBond/Bond#170]
I tried to make an Observable like this: Observable<AVPlayerItemStatus>(object: item, keyPath: "status") where item is an instance of AVPlayerItem.

However, it does not work because the Observable initializer tries to cast the value to AVPlayerItemStatus, but it gets an NSNumber back (which may be cast to Int, but not to the bridged enum).

if let value = object.valueForKeyPath(keyPath) as? Wrapped {
      self.init(value)
    } else {
      fatalError("Dear Sir/Madam, you are creating a Scalar of non-optional \(EventType.self) type, but the value at the given key path is nil or not of \(EventType.self) type. Please check the type or have your Scalar encapsulate optional type like Scalar<\(EventType.self)?>.")
    }

Perhaps, unsafe casting back to enum would be dangerous, so a comment or a note about this problem would suffice.

I currently worked around the problem by using Observable<Int> instead of Observable<AVPlayerItemStatus>

**Comment by srdanrasic** [comment]
Did you try working with NSNumber instead?

```swift
let status = Observable<NSNumber>(object: item, keyPath: "status")
```

**Comment by serieuxchat** [comment]
It works with Int, so it was enough for me:
let status = Observable<Int>(object: item, keyPath: "status")

**Comment by srdanrasic** [comment]
It's OK to do cast in your case because the value is coming from AVPlayerItemStatus enumeration.

```swift
let status = Observable<Int>(object: item, keyPath: "status")
  
status.observe { rawStatus in
  let status = AVPlayerItemStatus(rawValue: rawStatus)!
  ...
}
```

**Comment by serieuxchat** [comment]
I was wondering if it were possible to detect that Wrapped is an enum with a raw value and try to do the cast inside the constructor... (probably not simple in any case).

**Comment by srdanrasic** [comment]
Yeah, not simple at the moment...
