### ISSUE TITLE
Map shouldn't lose type information when unnecessary.

### ISSUE THREAD

**Issue by adamkuipers** [SwiftBond/Bond#173]
Calling combinators on Observables should produce another Observable.

e.g. `Observable(1).map { $0 + 1 }.value` should compile.

**Comment by srdanrasic** [comment]
It's actually difficult problem. Observables are expected to have value. Currently all methods return EventProducer because some of them might not produce a value, like `Observable(1).filter { false }.value`

**Comment by adamkuipers** [comment]
Yeah, I hadn't thought about how it would work with other methods. Thanks for the insight.
