### ISSUE TITLE
calls to crystallize after insert on the observableArray doesnt work as expected

### ISSUE THREAD

**Issue by krunalsheth** [SwiftBond/Bond#176]
Here's a test code.

func testObservableArrayFilter() {

	let array = ObservableArray<Int>([1, 2, 3])
	array.insert(7, atIndex: 0) // 7, 1, 2, 3
	XCTAssert(array.count == 4)

	let filtered = array.filter{ e in e % 2 == 0 }.crystallize()
	XCTAssert(filtered.array == [2])
}

if I move initialization on filtered  before array.insert, it works as expected.

**Comment by srdanrasic** [comment]
That sounds bad :)

**Comment by srdanrasic** [comment]
Fixed in v4.0.2.
