### ISSUE TITLE
Provide way to disable animation on tableview inserts/deletes

### ISSUE THREAD

**Issue by kentwilliam** [SwiftBond/Bond#177]
Please forgive me if this is already supported, but I've been looking through the source and it appears that `.Automatic` is the name of the game when it comes to tableview updates. 

https://github.com/SwiftBond/Bond/blob/45d8a72a1f49848a0c8f460068b41df1097fff55/Bond/Extensions/iOS/UITableView%2BBond.swift

Our project would rather disable animation altogether—is this on the roadmap at all?

**Comment by srdanrasic** [comment]
It should be a simple improvement. I'll try to do it in next few days.

**Comment by srdanrasic** [comment]
Improved in v4.0.2. Use proxy delegate in bindTo method to specify animation.

**Comment by kentwilliam** [comment]
Perfect, thank you!
