### ISSUE TITLE
UITextField shortcut expansion issue

### ISSUE THREAD

**Issue by advantis** [SwiftBond/Bond#18]
Today I came across the following issue: when typing a shortcut into `UITextField` (can be defined at Settings.app → General → Keyboard → Shortcuts) and after pressing Return button on keyboard shortcut expands, text is replaced but nothing happens from the corresponding binding's perspective. That's because `UIControlEventEditingChanged` is not sent in this case. Just FYI. I don't think there's an easy way to fix this without resorting to some ugly hacks. RAC also seems to suffer from the same issue.

**Comment by srdanrasic** [comment]
Hi @advantis, thanks for reporting this. It's unfortunate that iOS doesn't send notifications in that case.

I'll leave it as is for now...

**Comment by clooth** [comment]
@advantis I solved this in my application by running the validations manually (in my case for email-addresses) on the return handler where I switch to the next UITextField.
