### ISSUE TITLE
onReuseBag

### ISSUE THREAD

**Issue by okla** [SwiftBond/Bond#181]
In readme example I see

```
repository.name
    .bindTo(cell.nameLabel.bnd_text)
    .disposeIn(cell.onReuseBag)
```

What is `onReuseBag` and where can I find it? And what if I use `bnd_bag` instead? Will it cause memory leak?

**Comment by srdanrasic** [comment]
That is something you need to create and dispose in prepareForReuse :)

```swift

class MyTableViewCell: UITableViewCell {
  let onReuseBag = DisposeBag()

  override func prepareForReuse() {
    onReuseBag.dispose()
  }
}
```

`bnd_bag` is automatically provided as an extension to NSObject and is disposed when object is deallocated.

**Comment by okla** [comment]
@srdanrasic got it, thanks!

**Comment by richlowenberg** [comment]
Are there any good explanations of how and when to use these DisposeBags? Thanks!
