### ISSUE TITLE
Best way to control Submit button enabled/disabled, based on form inputs

### ISSUE THREAD

**Issue by joshavant** [SwiftBond/Bond#189]
Out of curiosity, do you think this is the best approach to controlling the enable/disabled status of a Submit button for a user input form with multiple inputs?

```
combineLatest(firstNameTextField.bnd_text,
        lastNameTextField.bnd_text,
        emailAddressTextField.bnd_text,
        passwordTextField.bnd_text,
        sessionUpdateInProgress).map {
            (firstName: String?, lastName: String?, emailAddress: String?, password: String?, updateInProgress: Bool) -> Bool in
            if let aFirstName = firstName,
                    aLastName = lastName,
                    anEmailAddress = emailAddress,
                    aPassword = password {
                    return aFirstName.characters.count > 0 &&
                            aLastName.characters.count > 0 &&
                            Globals.isValidEmailAddress(anEmailAddress) &&
                            aPassword.characters.count > 0 &&
                            !updateInProgress
            }
            return false
        }.bindTo(signUpButton.bnd_enabled)
```

Also, while I haven't noticed any immediate performance problems, do you think this is a performant pattern to use at scale, with large numbers of combines?

**Comment by srdanrasic** [comment]
Hi  @joshavant,

I would not worry about performance. Having hundreds or even thousands variables would probably not be noticeable. 

On the other hand, you might improve readability by mapping all the inputs to a boolean value:

```swift
func isEntered(string: String?) -> Bool {
  if let string = string {
    return string.characters.count > 0
  } else {
    return false
  }
}

combineLatest(firstNameTextField.bnd_text.map(isEntered),
  lastNameTextField.bnd_text.map(isEntered),
  emailAddressTextField.bnd_text.map(Globals.isValidEmailAddress),
  passwordTextField.bnd_text.map(isEntered),
  sessionUpdateInProgress).map {
    (firstName, lastName, emailAddress, password, updateInProgress) -> Bool in
      return firstName && lastName && emailAddress && password && !updateInProgress
  }.bindTo(signUpButton.bnd_enabled)
```

Assuming isValidEmailAddress can accept optional string.

**Comment by srdanrasic** [comment]
You could simplify it even more. Swift is so powerful. You can define extension on an array of boolean event producers that returns event producer that check whether all inputs are true...

```swift
public extension CollectionType where Generator.Element: EventProducerType, Generator.Element.EventType == Bool {
  
  public func allTrue() -> EventProducer<Bool> {
    return EventProducer(replayLength: 1) { sink in
      
      let compositeDisposable = CompositeDisposable()
      var truthMap = self.map { e in false }
      
      self.enumerate().forEach { (index, producer) in
        compositeDisposable += producer.observe { event in
          truthMap[index] = event
          sink(truthMap.reduce(true) { $0 && $1 })
        }
      }
      
      return compositeDisposable
    }
  }
}
```

Then you could do:

```swift
[
  firstNameTextField.bnd_text.map(isEntered),
  lastNameTextField.bnd_text.map(isEntered),
  emailAddressTextField.bnd_text.map(Globals.isValidEmailAddress),
  passwordTextField.bnd_text.map(isEntered),
  sessionUpdateInProgress.map { !$0 }
].allTrue().bindTo(signUpButton.bnd_enabled)
```

(I'm writing this in the browser, I didn't test this code)

**Comment by joshavant** [comment]
Awesome suggestions, @srdanrasic! Thank you!

You're great with the browser... that all (mostly) worked. My only change was to declare the extension, like so:
`extension CollectionType where Generator.Element: EventProducerType, Generator.Element.EventType == Bool {`
(tl;dr - dropped the leading `public`)

Also, instead of passing a function in (because have to validate lots of forms around the app), I decided to do this:
`firstNameTextField.bnd_text.map{ !($0?.isEmpty ?? true) }`

It's the most pretty or readable, but it also means I don't have to add/maintain a small, one-off extension for `String` or `CollectionType` just to check `count > 0`.
