### ISSUE TITLE
Retain Cycle on EventProducerType.crystallize

### ISSUE THREAD

**Issue by fvalbuena** [SwiftBond/Bond#191]
Hey, while using instruments... I noticed there were many objects retained while using the crystallize function... looking at the implementation you do:

```swift
array.deinitDisposable += skip(replayLength).observe { event in
      array?.applyOperation(event.operation)
      return
}
```

the block is retaining the array... since the disposable it's stored in deinitDisposable which at the same time is owned by array... this causes a retain cycle... it needs a [weak] or [unowned] there...

thanks, I'd appreciate this fix could come in the next release... I really like SwiftBond :+1:

**Comment by srdanrasic** [comment]
Thank you, this was bad! Fix is out in v4.0.3. Thanks again! :)
