### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#192]
Is it coming?

**Comment by srdanrasic** [comment]
I'd like to add it but don't have much time to do it. Hope I'll manage something in the following weeks.

**Comment by zdenektopic** [comment]
You've got a PR for tvOS basic support - https://github.com/SwiftBond/Bond/pull/186

**Comment by srdanrasic** [comment]
V4.1 is out with basic support for tvOS.
