### ISSUE TITLE
Merge multiple EventProducers into a single EventProducer

### ISSUE THREAD

**Issue by manas-chaudhari** [SwiftBond/Bond#195]
I have an array of `EventProducer` objects of same `EventType`. How can I merge them into a single `EventProducer`?
The [merge](https://github.com/SwiftBond/Bond#merge) method works on `EventProducer<EventProducerType>`, but I couldn't find any method to create an `EventProducer` from an array of `EventProducer` objects.

## Scenario

I have to show a list in a tableView. Thus, I create an `ObservableArray` of view models and bind to the tableView. Each view model exposes a few eventProducers for certain actions that can happen on the cell. 
There are several examples for such actions such as:
- Button Tapped
- Cell Selected
- Some Gestures

There's a view model for the entire page, which listens for these events and updates its model. In order to do some action for each cell independently, such as displaying a message, adding an observer by looping over all the producers can work. 
If we want to do something which is based on previous selection (like reacting to distinct selections), this gets messy. It cannot be done without introducing new variables in a non-reactive style. Any additional operations will also have to be done inside the for loop, which isn't clean.
In order to do this effectively, a single eventProducer with the index of the cell where the event happened needs to be created.
Then, we can make use of all reactive operators such as `distinct`, `throttle` on this single producer.

## Current Implementation

For simplicity, consider that the list of view models is static. Whatever is done below, can be implemented on an `ObservableArray`. It'll require some additional cleaning up of disposables which isn't the point here.

```
class ItemViewModel {
    let selected: EventProducer<Void> = EventProducer()
    let name: String = ""
}

func showMessage(name: String) {
    // Do something
    /*
     Any operations such as distinct/throttle will have to be done here.
     We can create another EventProducer here and fire events into that, but
     we are still left with the boiler plate of declaring an eventProducer and 
     firing events into it.
     */
}

let vms = [ItemViewModel]()
let selectedEvents = vms.map { vm in vm.selected.map { vm.name } }

for event in selectedEvents {
    event.observe(showMessage)
}
```

## Proposal

As the current `merge` function requires an `EventProducer<EventProducerType>`, I think we can add a convenience function to merge events from an array.

```
public func merge<A: EventProducerType>(eventProducers: [A]) -> EventProducer<A.EventType> {
    return EventProducer<A>(replayLength: eventProducers.count) { sink in
        eventProducers.forEach(sink)
        return nil
    }.merge()
}
```
With this we can do the selection handling as follows:
```
let selected = merge(selectedEvents)
selected.distinct().observe(showMessage)
```

**Comment by srdanrasic** [comment]
Thanks @manas-chaudhari. This sounds like a reasonable solution, but I don't think that your implementation is correct. You probably want something like this:

```swift
public func combineLatest<S: SequenceType where S.Generator.Element: EventProducerType>(sequence: S) -> EventProducer<S.Generator.Element.EventType> {
  return EventProducer(replayLength: 0) { sink in
    let compositeDisposable = CompositeDisposable()
    sequence.forEach { producer in
      compositeDisposable += producer.observe(sink)
    }
    return compositeDisposable
  }
}
```

**Comment by manas-chaudhari** [comment]
Thanks @srdanrasic. This is more simple and generic. I was unnecessarily trying to reuse the available `merge` function. Will update the pull request.
