### ISSUE TITLE
Collection view header view implementation error

### ISSUE THREAD

**Issue by manishdubey-epita** [SwiftBond/Bond#204]
Hi,

I am making an application in which a timeline kind of collection view is required. I am using Bond framework to bind the datasource with the collection view. It was working fine until I tried to get UICollectionReusableView for the headers. I am getting below error and have no idea what to do:

![screen shot 2015-11-20 at 13 48 43](https://cloud.githubusercontent.com/assets/11277712/11300782/1337f84a-8f92-11e5-83bc-1085b77ad53b.png)

**Comment by manishdubey-epita** [comment]
This is my implementation of viewForSupplementaryElementOfKind :

func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView {
        let headerView: TimelineHeaderView = collectionView.dequeueReusableSupplementaryViewOfKind(kind, withReuseIdentifier: headerViewIdentifier, forIndexPath: indexPath) as! TimelineHeaderView
        let view = TimelineViewModel.observableDateArr
        headerView.dateLabel.text = TimelineViewModel.getDateLabelAtIndex(indexPath.section)
        return headerView
    }

**Comment by srdanrasic** [comment]
Make your view controller conform to `BNDCollectionViewProxyDataSource` protocol. Then in bindTo, pass you view controller as `proxyDataSource`.

```swift
class ViewController: UIViewController, BNDCollectionViewProxyDataSource {

  ...
  bindTo(collectionView, proxyDataSource: self) { ... }
  ...

  func collectionView(collectionView: UICollectionView, viewForSupplementaryElementOfKind kind: String, atIndexPath indexPath: NSIndexPath) -> UICollectionReusableView { ... }
}
```

Let me know if that works

**Comment by manishdubey-epita** [comment]
Thanks! It worked for me.

**Comment by manishdubey-epita** [comment]
Hi,

Sorry for reposting on this issue. The problem is that I am getting only one header. How should I make my data source array so that I get a 2 dimensional observable array? And how to bind this with collection view so that every header has designated cells?

my arrays:
class TimelineViewModel
{
    private static var _previousDate = ""
    private static var _arrayCleaned = false    
    static var cellContentsArray:[CellContent] = []
    static var observableCellsContentArray = ObservableArray(TimelineViewModel.cellContentsArray)

//formation of the array:
 for var i = 0; i < Int(TimelineViewModel.timeslotUtilList.size()); i++
            {
                let timeslot = timeslotUtilList.getWithInt(jint(i)) as! STMOTimeslot
                let date = timeslot.day.toDbString()
                let newCellContentObject = CellContent(_timeslot: timeslot, cellExpanded: false, _date: date)

                if (TimelineViewModel._previousDate == "") {
                    TimelineViewModel._previousDate = date
                }

                /*let timestamp = timeslot.timestampStart
                let day = timeslot.day
                let offset = timeslot.offset
                let newTimeslotObject = STMOTimeslot(long: timestamp, withSTMODay: day, withLong: offset)

                TimelineViewModel.cellContentsArray.insert(newCellContentObject
                    , atIndex: 0)
                if !TimelineViewModel._dates.contains(date){
                    TimelineViewModel._dates.append(date)
                }

                if (TimelineViewModel._previousDate != date){
                    TimelineViewModel._previousDate = date
                    TimelineViewModel.observableCellsContentArray.performBatchUpdates { cellContent in
                        if (TimelineViewModel._arrayCleaned == false){
                            cellContent.removeRange(0..<cellContent.count)
                            TimelineViewModel._arrayCleaned = true
                            cellContent.extend(TimelineViewModel.cellContentsArray)
                        }
                        cellContent.extend(TimelineViewModel.cellContentsArray)
                        TimelineViewModel.cellContentsArray.removeAll()
                    }
                }
            }
*******************
binding in collection view:
TimelineViewModel.observableCellsContentArray.lift().bindTo(collectionView, proxyDataSource: self) { indexPath, cellContent, collectionView in
            let cell = collectionView.dequeueReusableCellWithReuseIdentifier(self.identifier, forIndexPath:   indexPath) as! CollectionViewCell
            let timeslotAtIndexPath = cellContent[indexPath.section][indexPath.row]._timeslot!
            cell.layer.borderWidth = 0.5
            cell.activityLabel.text = TimelineViewModel.getActivityString(timeslotAtIndexPath)
            cell.placeLabel.text = TimelineViewModel.getLocationString(timeslotAtIndexPath)
            return cell
        }


Thanks in advance for your help!!!

**Comment by srdanrasic** [comment]
Are you saying that you need two (or more) sections in your collection view? To do that, you must have observable array of observable arrays...

```let content: ObservableArray<ObservableArray<Content>> ...```

You work with that just as with any 2D array `[[...]]`. You don't need `lift` when binding 2D array.

Please put you code in code blocks, it's hard to read it like this...
https://help.github.com/articles/github-flavored-markdown/#syntax-highlighting

**Comment by manishdubey-epita** [comment]
Thank! I will try that. And sorry for putting the code in unreadable format.

**Comment by manishdubey-epita** [comment]
Yes it worked. Thanks!
