### ISSUE TITLE
No way to insert, delete or update without animation in UITableView+Bond.swift

### ISSUE THREAD

**Issue by morizotter** [SwiftBond/Bond#209]
If using BNDTableViewProxyDatasource:

```
func tableView(tableView: UITableView, animationForRowAtIndexPaths indexPaths: [NSIndexPath]) -> UITableViewRowAnimation {
  return .None
}

func tableView(tableView: UITableView, animationForRowInSections sections: Set<Int>) -> UITableViewRowAnimation {
  return .None
}
```

![animation](https://cloud.githubusercontent.com/assets/536954/11452847/68523bc2-9638-11e5-80d0-d2a370843bba.gif)

`UITableViewRowAnimation.None`: 

![none](https://cloud.githubusercontent.com/assets/536954/11453138/6400ee7e-9642-11e5-8365-8376d5d36750.png)

UITableViewRowAnimation.None doesn't prevent animation. 

I think there are no way to insert, delete or update without animation.  I'll send pull request to fix this issue soon.

**Comment by ioswmtdeveloper** [comment]
Try inside UIView.animate method like below code, keep duration 0, delay 0:

`UIView.animate(withDuration: 0.0, delay: 0.0, options: .curveEaseInOut, animations: {[weak self] in
            yourtableview.deleteRows(at: arrRemoveIndex, with: UITableViewRowAnimation.none)
        })`
