### ISSUE TITLE
Remove Binding

### ISSUE THREAD

**Issue by manishdubey-epita** [SwiftBond/Bond#212]
Hi,

I am using bidirection binding between strings and  textFields. Theses bindings are done in a subview. I want to remove these bindings once the subview is removed:

```
        TimelineViewModel._actStr.bidirectionalBindTo(actTextField.bnd_text)
        TimelineViewModel._placeStr.bidirectionalBindTo(placeTextField.bnd_text)
        TimelineViewModel._roomStr.bidirectionalBindTo(roomTextField.bnd_text)
```

Thanks!!

**Comment by clooth** [comment]
Couldn't you use `dispose()` in your `willRemoveSubview` on the parent view? (Just throwing ideas.)

**Comment by srdanrasic** [comment]
Binding are automatically disposed (removed) when targets (text fields in your case) are deallocated. If you need to do that sometime earlier, store the disposable:

```swift
let disposable = TimelineViewModel._actStr.bidirectionalBindTo(actTextField.bnd_text)
```

And later when you need it dispose it as @clooth said:

```swift
disposable.dispose()
```

**Comment by manishdubey-epita** [comment]
Thanks @clooth and @srdanrasic  for the solution. I am very new to reactive programming and I have started with SwiftBond to learn it properly. It's amazing and I hope to get more support from here.
