### ISSUE TITLE
R: Add UICollectionView bond

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#22]
Bond is really amazing. What would be awesome to have is bond for UICollectionView as there is one for UITableView

**Comment by srdanrasic** [comment]
I completely agree with you Zdeněk. Will do as soon as I get some spare time.

**Comment by zdenektopic** [comment]
Awesome. I have one off-topic question tho. Why do you use dequeueResuable..... without indexPath? Can you use the one with indexPath?

**Comment by srdanrasic** [comment]
We don't have indexPath available in map function. Might be a good feature though in next version.

Do you need to use indexPath variant for some reason?

**Comment by zdenektopic** [comment]
Performance reasons obviously. Meaning you cant use map function tho. It is supposed to reuse instances of UITableViewCell. Map function just creates new array with all the cells already instantiated, which is not so good actually. 200 cells might take up some memory, specially if you are loading more as user scrolls down.

**Comment by zdenektopic** [comment]
I think you should refactor this into simple array ->> UITableViewBond, where bond holds the actual cell creation/reuse and configuration

**Comment by srdanrasic** [comment]
Array map is pull-based so it means that cells are created on demand. Check out this section: https://github.com/SwiftBond/Bond#map-and-filter

**Comment by zdenektopic** [comment]
I see. Nicely done. I can now see it also supports having different cells for each section.

**Comment by srdanrasic** [comment]
Implemented in v3.1.0.
