### ISSUE TITLE
Transform EventProducer into Observable

### ISSUE THREAD

**Issue by kafejo** [SwiftBond/Bond#225]
Is it possible to transform Observable via transform functions not to EventProducer but into Observable again?

Example:
```swift
let ob1 = Observable<String>("aaa")
let ob2: EventProducer<Int> = ob1.map { $0.characters.count }
```
And I would like to have ob2 as Observable, instead of EventProducer. Thanks

**Comment by manas-chaudhari** [comment]
You can bind an `EventProducer` to your observable.
```
let ob1 = Observable<String>("aaa")
let ob2 = Observable<Int>(1)
ob1.map { $0.characters.count }.bindTo(obj2)
```
May I know what's the use case for this? Do you intend to modify `obj2` via some other source?

**Comment by kafejo** [comment]
Thank you. I use Bond for KVO binding between model and view model in MVVM architecture. For example:
```
class Car: NSManagedObject {
    var currentSpeed: NSNumber?
}

class CarViewModel {
   let model: Car
   var disposeBag: [AnyObject]
   private(set) lazy var currentSpeed: String = {
       let currentSpeed = Observable<String>("") 
       let speed = Observable<Int?>(object: self.model, keypath: "currentSpeed").map { "\($0) km/h"}.bindTo(currentSpeed)
       self.disposeBad.append(speed)
       return currentSpeed
   }()   
}
```
Whenever the model's current speed changes, the view model's currentSpeed gets update and the views which are bound with it as well

**Comment by manas-chaudhari** [comment]
Okay. 
I am curious. Why not keep EventProducer in the view model instead?

**Comment by kafejo** [comment]
Because sometimes we don't need binding, only the value. For example in UITableViewCell when the table uses NSFetchedResultsController to update cells, binding is not necessary but rather overkill.
