### ISSUE TITLE
Bond Tutorial

### ISSUE THREAD

**Issue by micpringle** [SwiftBond/Bond#228]
Hey guys,

I wanted to let you know that we've _just_ published a tutorial on Bond over on [raywenderlich.com](http://raywenderlich.com).

You can find it here: [Bond Tutorial: Bindings in Swift](http://www.raywenderlich.com/123108/bond-tutorial)

Would be great to get your thoughts.

Thx!

**Comment by srdanrasic** [comment]
That's a great article, thank you! Awesome graphics too :)

**Comment by micpringle** [comment]
:+1:
