### ISSUE TITLE
asObservableFor

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#23]
Amazing helper.

I have just question about mapping it. Can I simply do 

    let title = Dynamic<String>.asObservableFor(model, keyPath: "competition.name", defaultValue: "").map { t -> String in t.uppercaseString }

without retaining the first Dynamic object returned by the asObservableFor?

Or is:
```
let dynName = Dynamic<String>.asObservableFor(model, keyPath: "competition.name", defaultValue: "")
let title = Dynamic<String>("")
dynName.map { t -> String in t.uppercaseString } ->> title
```
required?

**Comment by srdanrasic** [comment]
Yes, you can do that. Dynamic returned by `map` (or other similar functions) will retain source one.

**Comment by srdanrasic** [comment]
Just be careful when working with K-V observing that your Dynamic does not outlive observed object (`model` in your case) as discussed in #21.

**Comment by zdenektopic** [comment]
the object i am doing this in has strong reference to the model, so it should not be a problem i suppose, model can outlive Dynamic or they are both released at the same time
