### ISSUE TITLE
Crashed when create EventProducer Object on iOS 7, Xcode 7.3

### ISSUE THREAD

**Issue by liuduoios** [SwiftBond/Bond#249]
Crashed when create EventProducer Object on iOS 7
Xcode 7.3

Crashed here
```
let tmpSelfReference = Reference(weak: self)
```

**Comment by mikhaelt** [comment]
I got this issue in the same point, using Xcode 7.3 also.
Have any solution for this?

Thanks

**Comment by paulofaria** [comment]
oh man! me too! haha please tell me you found a solution! @srdanrasic any idea?

**Comment by srdanrasic** [comment]
Hmm, that is quite puzzling. Any additional information you can provide might help. Under what circumstances does it happen? What transformations are applied? Thanks!

**Comment by liuduoios** [comment]
This is a Swift 2.2 bug, update Xcode to 7.3.1 can solve this issue.
