### ISSUE TITLE
NS?

### ISSUE THREAD

**Issue by jeff-h** [SwiftBond/Bond#25]
Hi — I see integration with a bunch of UI* objects. What's the situation with NS*?

**Comment by srdanrasic** [comment]
If you're referring to Cocoa framework for OS X, there aren't any plans at the moment.

Feel free to contribute though :)

**Comment by jeff-h** [comment]
Hi — that's exactly what I meant; sorry I was a bit obtuse. I'll need to learn a bunch more before I'll be of any use on this :)
