### ISSUE TITLE
Map function - use created Dynamic or bind it to other Dynamic?

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#26]
I am doing this:
```
let dynDate = Dynamic<Double>.asObservableFor(model, keyPath: "validTo", defaultValue: 0).map { seconds -> NSDate in NSDate(timeIntervalSince1970: seconds / 1000) }
```

Now should I do this:
```
let relativeTime = Dynamic<String>("")
dynDate.map { d -> String in BETTimeFormatter.timeRelative(d) } ->> relativeTime
```
or
```
let relativeTime = dynDate.map { d -> String in BETTimeFormatter.timeRelative(d) }
```

Same with reduce, etc..

**Comment by srdanrasic** [comment]
Both should work, but second alternative is preferred way to go.

**Comment by zdenektopic** [comment]
Thanks, probably should mention this in READ ME. I know there are examples for UIViews only, so it makes sense to use binding, however when you have custom Dynamics like that, it seems natural to use created instance directly I guess.
