### ISSUE TITLE
Can't use Void with EventProducer.

### ISSUE THREAD

**Issue by RyogaK** [SwiftBond/Bond#263]
I tried to make `EventProducer<Void>`, `Observable<()>` and something like above, but in all cases XCode will hang.
Anyone know in detail this problem? or Bond doesn't support like this? 🙏

**Comment by CallumOz** [comment]
https://github.com/SwiftBond/Bond/blob/master/Bond/Extensions/iOS/UIButton%2BBond.swift#L35

`EventProducer<Void>` works, I have used it many times in my own project.
