### ISSUE TITLE
Why isn't bidirectionalBindTo commutative?

### ISSUE THREAD

**Issue by Benuuu** [SwiftBond/Bond#273]
I have a sample project with a simple textField.
```
    let stringObservable = Observable<String?>("")
    @IBOutlet weak var textField: UITextField!

    override func viewDidLoad() {
        super.viewDidLoad()
        stringObservable.value = "hello world"

        // textField.bnd_text.bidirectionalBindTo(stringObservable) // Example 1
        stringObservable.bidirectionalBindTo(textField.bnd_text) // Example 2

        stringObservable.observeNew { newString in
            print(newString)
        }
    }
```
I would expect both Example 1 and 2 to do the same thing, however Example 2 is the only one that populates the textField initially with "hello world".

The documentation in bidirectionalBindTo seems to indicate that it only does a one-way binding, but I'm assuming this is a typo.
```
    /// Establishes a one-way binding between the source and the bindable's sink
    /// and returns a disposable that can cancel observing.
    public func bidirectionalBindTo<B : BindableType where B : EventProducerType, B.EventType == Element, B.Element == EventType>(bindable: B) -> DisposableType
```

Am I mistaken in assuming that Example 1 and 2 should do the same thing, or is this a bug?

**Comment by srdanrasic** [comment]
Hi @Benuuu,

Both `textField` and `stringObservable` have initial value. In case of `textField` the initial value is `nil` but it's still a value of `String?` type. We have to take someones value as a starting point. Rule is that we take the initial value from the object on whom you call `bidirectionalBindTo`.

Hope this helps.

Yes, that is a typo in the documentation.

**Comment by Benuuu** [comment]
@srdanrasic thanks! that clears things up.
