### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by vulgur** [SwiftBond/Bond#278]
Well, after converting code to Swift 3 in my project and update Bond to v5, I got these error after carthage update:

*** Building scheme "Bond-iOS" in Bond.xcodeproj
** BUILD FAILED **

The following build commands failed:
       	CompileSwift normal arm64
       	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/wangshudao/Dev/workspace/github-projects/CodeReader/Carthage/Checkouts/Bond/Carthage/Checkouts/ReactiveKit/Sources/SignalProtocol.swift:685:7: error: closure use of non-escaping parameter 'context' may allow it to escape
/Users/wangshudao/Dev/workspace/github-projects/CodeReader/Carthage/Checkouts/Bond/Carthage/Checkouts/ReactiveKit/Sources/SignalProtocol.swift:772:9: error: closure use of non-escaping parameter 'context' may allow it to escape
/Users/wangshudao/Dev/workspace/github-projects/CodeReader/Carthage/Checkouts/Bond/Carthage/Checkouts/ReactiveKit/Sources/SignalProtocol.swift:771:27: error: closure use of non-escaping parameter 'context' may allow it to escape
A shell task (/usr/bin/xcrun xcodebuild -project /Users/wangshudao/Dev/workspace/github-projects/CodeReader/Carthage/Checkouts/Bond/Bond.xcodeproj -scheme Bond-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
       	CompileSwift normal arm64
       	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by ben73** [comment]
I'm have same error.

**Comment by ben73** [comment]
Fix: Just add next line to your Podfile
`pod 'ReactiveKit', :git => 'https://github.com/ReactiveKit/ReactiveKit.git', :tag => 'v3.0.0-beta2'`

**Comment by vulgur** [comment]
@ben73 Well, I've already add this line: github "ReactiveKit/ReactiveKit" ~> 3.0", and carthage download the v3.0.0-beta2, but it doesn't work.
I will try your solution.

**Comment by ben73** [comment]
@vulgur Fixed in [this commit](https://github.com/ReactiveKit/ReactiveKit/commit/4aef579b92110312291bb94507e03c7f78b3d3c6)

**Comment by vulgur** [comment]
@ben73 That's right it was fixed, but it just don't work in  carthage update.(Maybe it works by CocoaPods)

**Comment by srdanrasic** [comment]
I've just released v5.0.0-beta3. It should work fine with Carhage.

I'm having issues with CocoaPods. But I won't give up! :)

**Comment by vulgur** [comment]
Yes! It works in Beta-3! Great works!
