### ISSUE TITLE
TableView binding Error on Append 

### ISSUE THREAD

**Issue by EEimer** [SwiftBond/Bond#279]
Hi,

Today we switched from bond 4.xx to 5.0.0 beta3

we have some TableViews which use the bond binding to generate the TableViewCells.
When binding the TableView to an MutableObservableArray, the app crashes on "appending" or "inserting" elements to the array.
With bond 4.xx we have used the extend function 
```swift
names.extend([])
```
  but this function is not available anymore.

The most basic example: 

```swift
var names = MutableObservableArray(["foo","bar"])
names.bind(to: tableView) { posts, indexPath, tableView in
    print("\(posts[indexPath.row])")
    return UITableViewCell()
}
names.append("foobar")
```

Exception: 

 ``` 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid
 index path for use with UITableView.  Index paths passed to table view must contain exactly two
 indices specifying the section and row.  Please use the category on NSIndexPath in UITableView.h
 if possible.' 
```

We also tried to set an new array but this doesnt trigger an update on the tableview.
Any help is greatly appreciated.

**Comment by srdanrasic** [comment]
Ah, I know what is causing this. I'll have it fixed today.

**Comment by srdanrasic** [comment]
Hey @EEimer, this is now fixed in beta4.

Unfortunately, I can't release new version over CocoaPods because there are some issues with their servers. If you're using Carthage you should be fine, just update to beta4. Hopefully CocoaPods issues will be resolved soon.

**Comment by EEimer** [comment]
Thank you so much @srdanrasic ,  fortunately we use carthage :) 

Just cloned it -> works perfekt! 

Thanks for the awesome fast fix this awesome lib :)

**Comment by srdanrasic** [comment]
Great! Thanks for reporting this. We are still in beta so feedback like yours is very valuable.

**Comment by AnthonyMDev** [comment]
@srdanrasic Has a beta been pushed to CocoaPods with this yet? The CocoaPods issues have been resolved.
