### ISSUE TITLE
Crash on DynamicArray.removeAll(true/false)

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#28]
It is happening on one instance of an array.
Bond+Arrays.swift:499

ma array had 13 elements, the for loop got to idx 7 and crashed for obvious reason: there are only 6 elements left.

**Comment by srdanrasic** [comment]
Could you write a minimal example that exhibits that issue?

**Comment by zdenektopic** [comment]
Well, Ill start with description.
I have DynamicArray as property in my controller (A). I instantiate this controller (A) in another controller (B) and append elements to that DynamicArray (it has some map and filter function bound to it). It DynamicArray is bound to UITableViewDataSourceBond and the controller (A) is also a delegate for UITableView. Actually the controller (A) is UITableViewController. Controller A is child controller of controller B and I have didSelect... on A where I push controller C. And the crash happens on pop when controller B clears the array (property of controller A). Called via viewWillAppear.

**Comment by srdanrasic** [comment]
Looks like there is an issue in filter function of an array. Working on the fix...

**Comment by zdenektopic** [comment]
Yeah, I thought so. Currently blocking me, I cold do workaround by reassigning the property with new instance of DynamicArray but I give it a weekend if you can come up with a solution,

Btw, sorry for spamming you with issues, but Bond is awesome! :100: :+1:

**Comment by srdanrasic** [comment]
I give it less then a weekend :)

No problem, I actually appreciate that you're opening issues, it helps make this framework better.

**Comment by zdenektopic** [comment]
I have reproduced the issue for you:

```
let arr = DynamicArray<Int>(Array<Int>(count: 100, repeatedValue: 3))
        let filtered: DynamicArray<Int> = arr.filter { i -> Bool in i % 3 == 0 }
        let mapped: DynamicArray<String> = filtered.map { i -> String in "\(i*i)" }
        
        NSLog("arr: \(arr.value)")
        NSLog("filtered: \(filtered.value)")
        NSLog("mapped: \(mapped.value)")
        
        arr.removeAll(false)
```

**Comment by srdanrasic** [comment]
Thank you! It should be fixed now. Please check v3.3.0.

Note that map on array now accepts both object to transform and its index.

**Comment by zdenektopic** [comment]
Awesome, thanks!
