### ISSUE TITLE
Bond5 UITableView issue

### ISSUE THREAD

**Issue by robertodias180** [SwiftBond/Bond#280]
I have this code and for some reason the first cells on the screen appear correctly, but when i scroll the new cells won draw.

	var dataSource = MutableObservableArray<News> = MutableObservableArray([])

	dataSource.bind(to: self.newsTableView) { (dataSource, indexPath, tableView) -> UITableViewCell in

		...
	}

Also i am getting an error with:

	 let onReuseBag = DisposeBag()// Use of unresolved identifier 'DisposeBag'

is this a bug from this version or i am doing something wrong?

**Comment by srdanrasic** [comment]
Hi @robertodias180,

Make sure your data source is retained by someone. E.g. make it a property in your class.

For DisposeBag you'll have to `import ReactiveKit`. I'll see if I can do something anything that.

**Comment by robertodias180** [comment]
Hi @srdanrasic, 

the `import ReactiveKit` solve the DisposeBag issue. Thank you.

As for the data source it is a var inside a `static let sharedInstance: RSNewsManager = RSNewsManager()` so retained  it should not be a issue.

**Comment by srdanrasic** [comment]
Hmmm, very strange, I've never encounter such issue. At first is sounded like threading issues, but logic around that is so simple and I don't see any problems.

Can you confirm that the code that's creating cells in `bind(to:)` is actually being executed when you scroll down?

**Comment by robertodias180** [comment]
@srdanrasic i removed all pods and re-installed everything and it is working now.

Also i noticed that if you use this `var dataSource: MutableObservableArray <MutableObservableArray< News >>` it wont work as before.

Was sections support removed?

**Comment by srdanrasic** [comment]
@robertodias180, yes, but there is/will be alternative. Please check out https://github.com/SwiftBond/Bond/issues/284.

**Comment by robertodias180** [comment]
Thank you @srdanrasic
