### ISSUE TITLE
Reactive Delegates

### ISSUE THREAD

**Issue by MickCrozier** [SwiftBond/Bond#289]
I'm getting compiler errors using the example in the readme.md
```swift
extension UITableView {
  var selectedRow: Signal<Int> {
    return bnd_delegate.signal(for: #selector(UITableViewDelegate.tableView(_:didSelectRowAtIndexPath:))) { (_: UITableView, indexPath: NSIndexPath) in indexPath.row }
  }
}
```
I get: Cannot invoke 'signal' with an argument list of type '(for: Selector, (UITableView, IndexPath) -> Int)

Can anyone shed some light on what I'm doing wrong?
(Bond 5 beta6)

**Comment by srdanrasic** [comment]
Ah, I'll need to update readme. You should do this:

```swift
extension UITableView {
  var selectedRow: Signal1<Int> {
    return bnd_delegate.signal(for: #selector(UITableViewDelegate.tableView(_:didSelectRowAt:))) { (subject: PublishSubject1<Int>, _: UITableView, indexPath: NSIndexPath) in subject.next(indexPath.row) }
  }
}
```

You need additional first argument - a subject - that you use to send events to signal.

**Comment by MickCrozier** [comment]
Awesome - Thank You!
