### ISSUE TITLE
UITableViewDataSourceBond issue

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#29]
When I append some rows, remove them, and then append them again, the rows have wrong height until reload is called

**Comment by zdenektopic** [comment]
actually not even that, it fixes when i scroll the entire UITableViewController within UIPageViewController

**Comment by zdenektopic** [comment]
there are more issues, same as before when I have filter, map, filter UITableViewDataSourceBond on update does empty rows and stuff like that, its weird

**Comment by zdenektopic** [comment]
actually the issue with tableView simply happens when the content is bigger than tableview, meaning the table view is scrolling

**Comment by srdanrasic** [comment]
I don't see how could this be Bond related. It does not affect layout in any way. It just provides data...

**Comment by zdenektopic** [comment]
Yes, its weird, but when I used classic UITableViewDataSource delegate it worked fine, i have ArrayBond with reloadData() in each listener, and it just works.

**Comment by srdanrasic** [comment]
I was finally able to reproduce this... Working on it...

**Comment by srdanrasic** [comment]
Caused by caching. So sad... It was great feature which had to be removed. v3.4.1 includes the fix.
