### ISSUE TITLE
Commands support

### ISSUE THREAD

**Issue by nayzak** [SwiftBond/Bond#32]
It would be great if Bond library have commands (like in Xamarin Forms). I made some basic stuff for my own use, but if your are interested in it and if it's possible to add commands right into Bond library, feel free to take my example [here](https://github.com/nayzak/Commands-for-Bond).

For example we have ViewModel, and it contains some command:
```swift
let notBusy: Dynamic<Bool>
lazy var pushNextPage: Command<()> = Command(target: self, enabled: self.notBusy) {
    [unowned self] value, sender in
    self.doSomethingAsync()
}
```
And it binds to `UIButton` like so:
```swift
button ->> viewModel.pushNextPage
```

When `notBusy` changes it value, `UIButton` will also become enabled or disabled. And command executes on button's `touchUpInside:`.

**Comment by srdanrasic** [comment]
Hi Ian, thanks for the suggestions. I agree with you, that should be right direction in the development of Bond. I'm currently exploring some ideas, but have not committed on one yet.

Thinking about adding abstraction on top of Dynamic in form of value-less Signal. Something like Command could then act upon those signals instead of just upon dynamics. Basically more Reactive stuff...

**Comment by nayzak** [comment]
Thanks for answer, Srđan. Unfortunately my mind is lack of architecture patterns (shame on me). If I understood right, your goal is to make a library, not framework. I mean that Bond will include just all basic stuff that user needs. And with all this stuff everyone can make everything they need for specific solutions? If I'm right than there is no place for  something like commands in your library. Because in my opinion commands are not multipurpose. In my example they can be used for controls and controls passing themselves to command. For example sometimes it's better to show action sheet from view model. in this case passing some UIView subclass instance to command can be useful. Also specifically for controls command store some `Dynamic<Bool>` value for easy and obvious enabling\disabling of control. But in table view's case it's just necessary to pass row index to command if that command responsible for `select` action.
I'm sorry if it's difficult to understand me :) I'm not english speaking person.

**Comment by paulofaria** [comment]
@srdanrasic that idea about value-less signal is very nice. While playing with Bond i caught myself mapping to void quite sometimes, when I just wanted the signal.

**Comment by tonyarnold** [comment]
Something that allows me to bind a Command/Bond without having retain it in a property myself would be very, very welcome if that falls within the ideas you have for Signals.

**Comment by srdanrasic** [comment]
@tonyarnold that would require introducing Disposables. Not sure if it would fit in current architecture where Dynamics (Observables) do not retain Bonds (Observers).

**Comment by srdanrasic** [comment]
`observe` method in v4 solves this..
