### ISSUE TITLE
Read-only `Dynamic<T>`

### ISSUE THREAD

**Issue by wiruzx** [SwiftBond/Bond#34]
Is there some kind of read only `Dynamic<T>`, that couldn't be changed from the outside?

**Comment by srdanrasic** [comment]
Could you elaborate this? Why would you use it?

**Comment by wiruzx** [comment]
As I understand, in current implementation, it's possible to change someone's `Dynamic<T>` value.

I'd like to forbid users to change value inside of my `Dynamic` property.

Like in `ReactiveCocoa`'s implementation, where there are `RACSignal` which value you cannot change, and `RACSubject` with changeable value. Also `RACSubject` is a subclass of `RACSignal`, so you can use `RACSubject` inside the class and give `RACSignal` to outside.

**Comment by srdanrasic** [comment]
Then I have good news for you - signals are work in progress - hope they'll be out by next weekend. 

Similarly to RC, Dynamic will be improved to extend Signal. Everything will be backward compatible.

**Comment by wiruzx** [comment]
That's great

**Comment by TadeasKriz** [comment]
Hi, any progress on this feature? Thanks.

**Comment by srdanrasic** [comment]
Hi @TadeasKriz, first beta version of Bond 4 with something like this will come out by the end of the week.

**Comment by TadeasKriz** [comment]
@srdanrasic Awesome! Thanks! Btw, are you thinking about including the rename in the new major release as well as talked in #47? :)

**Comment by srdanrasic** [comment]
Yes, we will finally have real Observables and much more. Whole architecture has been revisited. I believe it's much better, but I'm looking forward to hear feedback from all of you active here before final release :) I'll be pushing next version in following days as I polish some details.

**Comment by thedevme** [comment]
How long do you think it will be before Bond 4 is out of beta?

**Comment by srdanrasic** [comment]
@thedevme The goal is September 9th.
