### ISSUE TITLE
Support iOS 7.0 with cocoapods.

### ISSUE THREAD

**Issue by huyphams** [SwiftBond/Bond#36]
Hi guys,

I really like your work.
But I had a problem, my project still supports iOS 7.0. I hope you can down version of Bond in Cocoapods from 8.0 to 7.0.

Huy.

**Comment by zdenektopic** [comment]
it wont work with iOS 7 since it is written in Swift. It requires compiling the po as Dynamic Framework which can be embedded into iOS 8 deployment targets

**Comment by huyphams** [comment]
It works fine if you include Bond as Dynamic Framework with `optional` option. I did a lot of research about using Dynamic Framework in Swift with iOS7. :dancer:

**Comment by zdenektopic** [comment]
interesting, could you post some link or anything that refers to this?

**Comment by huyphams** [comment]
Here bro :dancer: 

http://quellish.tumblr.com/post/103107323582/dynamic-frameworks-on-ios-7

**Comment by huyphams** [comment]
But there are no Dynamic Frameworking linking in Cocoapods. Cocoapods imports Bond source code directly to your project, so you don't need to worry about that issue.

**Comment by srdanrasic** [comment]
Huy,

Check out v3.4.2. I lowered deployment target to 7.0. Give us your feedback if it works. Thanks

**Comment by zdenektopic** [comment]
Cocoapods adds Swift source code to the project? Didnt know about that :O

**Comment by huyphams** [comment]
@zdenektopic  sorry about that, in switf it's must be framework.

@srdanrasic thank you, I'll give a try right now.

**Comment by huyphams** [comment]
Hi zdenektopic,
It works as expected, but I don't know Apple accept or reject if my project use Dynamic Framework target to 7.0

**Comment by zdenektopic** [comment]
Well it is weak-linked, it builds with stable release version of Xcode so I suppose they should accept it? Specially if Cocoapods supports dynamic frameworks with deployment target 7.0

**Comment by huyphams** [comment]
Many thanks :dancer:

**Comment by zdenektopic** [comment]
I get `ld: embedded dylibs/frameworks are only supported on iOS 8.0 and later (@rpath/Bond.framework/Bond) for architecture arm64` when trying to compile for iOS 7.

**Comment by huyphams** [comment]
It's an error or warning?

**Comment by zdenektopic** [comment]
It was an error. Solved, see my edit.

**Comment by zdenektopic** [comment]
however, i am kinda sure this will only work if the application is running on iOS 8. If you run it on iOS 7 it will crash. Right?

**Comment by huyphams** [comment]
It won't crash if in your framework does not contain "App extension". App extension only supports iOS > 8.0.

**Comment by PrideChung** [comment]
@huyphams How to write the `Podfile` to specify Bond should be weak linked? I'm eager to know, thanks.
