### ISSUE TITLE
Chaining functions (map, filter and etc.)

### ISSUE THREAD

**Issue by nayzak** [SwiftBond/Bond#40]
Probably I'm missing something while trying to chain ```filter``` and ```map``` functions. It's just not working as expected. If I do something like this: ```someDyn.filter { $0 > 0 } ->| someBond``` it works fine. But when I add ```map``` after ```filter``` than ```map``` closure calls independently from ```filter```:
```swift
someDyn
    .filter { $0 > 0 } 
    .map { println("I'm called every time.") } 
->| someBond
```

**Comment by tonyarnold** [comment]
I'm seeing the same thing. Filters don't seem to be filtering:

```swift
someDyn
        .filter { $0 != nil }
        .map { $0.doSomething() } // Called every time
        ->> someBond
```

**Comment by tonyarnold** [comment]
My filters seem to work if they're strictly Bool types — any kind of more advanced check just fails.

**Comment by srdanrasic** [comment]
Thanks for reporting this. Should be fixed. Please check out v3.5.0.

**Comment by tonyarnold** [comment]
Thanks! The 3.5.1 release cleared up all the problems I was seeing :)
