### ISSUE TITLE
Extending UIView to add dynWidth property

### ISSUE THREAD

**Issue by gghhjj** [SwiftBond/Bond#41]
You've done a wonderful job with the Bond library! I've used it in two of my projects and it works great!
Now I would like extend it a little bit in my new project. Mainly, I want to add `dynWidth` property to UIView. I tried to replicate your code from `Bond+UIView.swift`. But I am stumbled at `d.retain(bond)`. I cannot do it from my ViewController, because your method is marked `internal`. Am I doing something wrong, or you library is not designed to be extended the way I want it to be?

```
private var widthDynamicHandleUIView: UInt8 = 0;

extension UIView {
    
    public var dynWidth: Dynamic<CGFloat> {
        if let d: AnyObject = objc_getAssociatedObject(self, &widthDynamicHandleUIView) {
            return (d as? Dynamic<CGFloat>)!
        } else {
            let d = InternalDynamic<CGFloat>(self.frame.width, faulty:false)
            let bond = Bond<CGFloat>() { [weak self] v in if let s = self {
                var viewFrame = s.frame
                viewFrame.size.width = v
                s.frame = viewFrame
                }
            }
            d.bindTo(bond, fire: false, strongly: false)
            //d.retain(bond)
            objc_setAssociatedObject(self, &widthDynamicHandleUIView, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
            return d
        }
    }

}

```

Thank you!

**Comment by srdanrasic** [comment]
I've made them public. Check out v3.5.1. Thanks.
