### ISSUE TITLE
Map proxy - caching needed!

### ISSUE THREAD

**Issue by zdenektopic** [SwiftBond/Bond#44]
Without that caching, each time I access the map proxy element, it is recreated and that causes me real pain sinceI have some status saved in my viewModels.

Scenario:
I have DynamicArray of Models retreived from api. That dynamic array I have mapped to DynamicArray of ViewModels that have some "status" Dynamic and this status is lost when I access the ViewModel another time :(

**Comment by srdanrasic** [comment]
Unfortunately, caching would introduce more problems than it would fix so this will not be implemented.

You should aim for map/filter/reduce functions to be pure functional - they should not change state of the object and should produce same result on each run.

**Comment by zdenektopic** [comment]
Well I currently solved this by proxying this thru separate ArrayBond that inserts/updates/deletes "mapped" objects to "proxy" array.
