### ISSUE TITLE
Discussion about naming

### ISSUE THREAD

**Issue by tonyarnold** [SwiftBond/Bond#47]
Please feel free to close this issue if you disagree, but I don't think the current names of some of the classes in this library reflect their purpose as well as they could. 

For many Cocoa developers, words like "bind", "bindings" and "observer" are familiar due to the long-standing Cocoa Bindings and KVO that this library replaces. 

I think it might make things a little easier to follow for long time Cocoa developers if the class names were closer to their equivalents in Cocoa:

- `Dynamic` could become `Observable`
- `InternalDynamic` could become `RetainingObservable` (or some variant thereof — maybe `StrongObservable`)
- `Bond` becomes `Binding` (this one is debatable given that "bond" isn't inaccurate)

These are just suggestions, but I'm hoping others have thoughts and input on this. 

/cc @raven

**Comment by srdanrasic** [comment]
Thank you @tonyarnold for bringing this up. I'm open to changes, but I'd like to see additional opinions.

Renaming `Dynamic` would require major version number change so that would potentially be part of next major release. I don't like the idea of doing major release just because of a rename.

There are no concrete plans for next major release yet - currently experimenting with signals that would be valueless abstractions of Dynamics.

**Comment by raven** [comment]
I found Dynamic to be somewhat confusing as well. Whilst reading your initial blog post I was following along ok, but after cloning and playing with the framework I was lost again and had to force a mental mapping. Also as `dynamic` is a declaration modifier in Swift, that can also lead to confusion.

**Comment by srdanrasic** [comment]
/cc @hip4yes @sync @lyricsboy @zdenektopic @advantis

Feel free to give your feedback.

**Comment by advantis** [comment]
Agree. To me `Dynamic` sounds more like a physics term. And `InternalDynamic` is quite obscure (but it's internal after all :). But this definitely requires a major version change, so we could put it on hold for a while.

**Comment by sync** [comment]
I don't mind ```Observable```, also```Binding``` could lead to confusion

**Comment by lyricsboy** [comment]
While I don't have a strong opinion, I will note that the first thing that comes to mind when I hear `Observable` is [Java](https://docs.oracle.com/javase/7/docs/api/java/util/Observable.html). :japanese_goblin:

**Comment by srdanrasic** [comment]
Renamed to Observable in v4.
