### ISSUE TITLE
Listener only called once

### ISSUE THREAD

**Issue by raphaelmor** [SwiftBond/Bond#5]
Using __Bond 2.0.1__,  in an empty project
When I write this basic code :
```swift
var foo = Dynamic<Int>(0)

foo ->> { foo in
    println("foo changed: \(foo)")
}

foo.value = 1
foo.value = 2
foo.value = 3
foo.value = 4
```
It logs :
```
foo changed: 0
```
but I think it should do this :
```
foo changed: 0
foo changed: 1
foo changed: 2
foo changed: 3
foo changed: 4
```

**Comment by srdanrasic** [comment]
Hi Raphaël, this is actually a feature. Bond exists while it is retained by someone. Designated Bonds on UIKit objects are retained by those objects. You should retain a Bond you create For example, you can save it in a property.

```swift
var myBond: Bond<String>?

...

self.myBond = foo ->> { foo in
    println("foo changed: \(foo)")
}
```

Thanks for the issue though, documentation was probably not clear on this, will have to improve it.

**Comment by raphaelmor** [comment]
Thanks, I was going nuts ! 
Yes most of the documentation is centered around UIKit items.
I'll see if I have time to propose a PR for the doc.

Thank you for the quick answer!
