### ISSUE TITLE
Setting DynamicArray.value should trigger change notifications

### ISSUE THREAD

**Issue by adly-holler** [SwiftBond/Bond#50]
It could be either "remove all" -> "insert all new", or it could be some special "set" operation (which would correspond to `UITableView.reloadData`). I think the `set` operation makes the most sense, to avoid wasting performance when changing 10000 items to 10000 different items.

**Comment by adly-holler** [comment]
Implemented in #51

**Comment by srdanrasic** [comment]
Tagged as v3.7.0.
