### ISSUE TITLE
Using a simple `Bond<T>` to propagate side effects

### ISSUE THREAD

**Issue by JustinTulloss** [SwiftBond/Bond#53]
I'm having some trouble figuring out how to use a bond for things that are not necessarily value transforms.

For instance, if I want to change the height of my label based on the updated text, I thought I could do something like this:
```swift
textLabel.dynText ->> Bond<String>() { _ in
    textLabel.sizeToFit()
}
```

However, that seems to only fire once. Changing the textLabel (even via another bond) does not cause the function to fire again.

Am I missing something?

**Comment by zdenektopic** [comment]
you need to retain the bond

**Comment by JustinTulloss** [comment]
Ok. Seems like I probably should have thought of that, but it wasn't obvious to me from the docs.

Thanks!

**Comment by JustinTulloss** [comment]
(And I see that it's explicitly stated in the docs now, it's just not actually spelled out in the examples)
