### ISSUE TITLE
NSButton is extended to work with 'state' - how can I use it with 'enabled' instead?

### ISSUE THREAD

**Issue by juandent** [SwiftBond/Bond#55]
The NSButton class is extended to deal with 'state' as its dynamic value. Short of changing this extension, how can I make it work where 'enabled' property is the dynamic value I want to observe?

something tells me there must be way yet ???

Thanks in advance,
Juan Dent

**Comment by tonyarnold** [comment]
Just use `myButton.dynEnabled` — NSButton is a subclass of NSControl. `dynEnabled` is included as part of the NSControl Bond extensions.

**Comment by juandent** [comment]
Thanks!!!
Sorry hadn't seen that!!
