### ISSUE TITLE
class TextFieldDynamicHelper must allow textChanged to be public!

### ISSUE THREAD

**Issue by juandent** [SwiftBond/Bond#56]
class TextFieldDynamicHelper: NSObject {

    weak var control: NSTextField?
    var listener: (String -> Void)?

    init(control: NSTextField) {
        self.control = control
        super.init()
        control.target = self
        control.action = Selector("textChanged:")
    }

    //private JDH corrected
    func textChanged(sender: AnyObject?) {
        self.listener?(control?.stringValue ?? "")
    }
}

The method textChanged must be accessible from outside this file or else you get "unknown selector textChanged: sent to TextFieldDynamicHelper

Juan Dent

**Comment by juandent** [comment]
Thanks!

**Comment by juandent** [comment]
version 3.7.4 has not corrected this problem... @objc does not solve it. Only eliminating private qualifier will work!

Juan

**Comment by srdanrasic** [comment]
That's sad. Will remove it...

**Comment by srdanrasic** [comment]
Fixed in v3.8.
