### ISSUE TITLE
Set nil value on relation field of NSManagedObject throw NSInvalidArgumentException

### ISSUE THREAD

**Issue by ktomek** [SwiftBond/Bond#57]
```
dynamicObservableFor<T>(object: NSObject, #keyPath: String, #from: AnyObject? -> T, #to: T -> AnyObject?)
```
When using  KVO binding  I'm not able to set nil on Dynamic object. 
The keyPath is pointing on relation property on NSManagedObject.
I'm getting:
```
ERROR:NSInvalidArgumentException -[NSNull managedObjectContext]: unrecognized selector sent to instance
```

The reason is when we want to set nil value, then NSNull object is set. CoreData check that relation is != nil and then try to check NSManagedContextObject on NSNull

The bug is here
```
object.setValue(to(value) ?? NSNull(), forKey: keyPath)
```

**Comment by srdanrasic** [comment]
@ktomek, thanks for reporting this and sorry for not getting it fixed earlier. Fix available in v3.7.3.
