### ISSUE TITLE
Dynamic property not firing

### ISSUE THREAD

**Issue by whateverx** [SwiftBond/Bond#62]
I want to add a new Dynamic property to UIView

```
private var FrameDynamicHandleUIView: UInt8 = 0;

extension UIView {
    
    
    public var dynFrame: Dynamic<CGRect> {
        if let d: AnyObject = objc_getAssociatedObject(self, &FrameDynamicHandleUIView) {
            return (d as? Dynamic<CGRect>)!
        } else {
            let d = InternalDynamic<CGRect>(self.frame ?? CGRectZero)
            let bond = Bond<CGRect>() { [weak self] v in if let s = self { s.frame = v } }
            d.bindTo(bond, fire: false, strongly: false)
            d.retain(bond)
            objc_setAssociatedObject(self, &FrameDynamicHandleUIView, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
            return d
        }
    } 
}

```
and in my view
```
class customView:UIView{

...

   lazy var frameListener:Bond<CGRect> = Bond<CGRect>(){ [unowned self] frame in
        
        
        println("not firing")
    
    }
    
    func bind(){
        
        
        self.dynFrame ->| frameListener
    
    }
}
```
but ```frameListener``` is not firing when I change the View's ```.frame``` ( I had no success on either ```.origin```, ```.origin.y``` etc..), Am I doing something wrong ?

**Comment by srdanrasic** [comment]
If will fire if you change its `dynFrame` property. 

If you really need to observe `frame` changes, you could create a Dynamic from KVO:

```swift
   lazy var frameListener:Bond<CGRect> = Bond<CGRect>(){ [unowned self] frame in
        println("firing :D")
    }

    func bind() {
        dynamicObservableFor(view, keyPath: "frame", defaultValue: CGRectZero) ->| frameListener
    }
}
```

**Comment by whateverx** [comment]
Thank you, got it for ```dynFrame```

Using  Bond 3.7.2, I was playing with ```dynamicObservableFor``` but it throw me an error during the cast of the generic T on this line
```swift
public func dynamicObservableFor<T>(object: NSObject, #keyPath: String, #defaultValue: T) -> Dynamic<T> {
...
let value: T = (keyPathValue != nil) ? (keyPathValue as? T)! : defaultValue
```
```Could not cast value of type 'NSConcreteValue' (0x1740576b8) to 'C.CGRect' (0x1002c5f80)```

 i'll try to find out what is going wrong

**Comment by whateverx** [comment]
I had to use ```NSValue``` for the ```defaultValue``` and map to  ```CGRect``` because ```object.valueForKeyPath(keyPath)```return  an NSValue 
now it works great !
 ```swift
dynamicObservableFor(self, keyPath: "frame", defaultValue:NSValue(CGRect: CGRectZero)).map{$0.CGRectValue()} ->| frameListener
```
is there a better way ?

**Comment by srdanrasic** [comment]
Yeah, that's due to unfortunate differences between ObjC and Swift. There is another way to create Dynamic from KVO property. It allows you to manually convert object. You need to pass two closure. One that converts AnyObject? to CGRect, and one other way round.

```swift
dynamicObservableFor(self, keyPath: "frame", from: { $0?.CGRectValue() ?? CGRectZero }, to: { NSValue(CGRect: $0) })
```

**Comment by whateverx** [comment]
The second way seems to be better
You've done an amazing job with Swift Bond, thank you!
