### ISSUE TITLE
IMK STALL detected, *please Report* your user scenario in <rdar://problem/16792073> - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (16.02 secs)

### ISSUE THREAD

**Issue by juandent** [SwiftBond/Bond#63]
I am getting this error when I run a small sample app:

IMK Stall detected, please Report your user scenario in rdar://problem/16792073 - (imkxpc_bundleIdentifierWithReply:) block performed very slowly (16.02 secs)

I run MAC OS X 10.10.3 on MacBookPro

??

Thanks.,
Juan Dent

**Comment by srdanrasic** [comment]
Are you sure this is related to Bond?

**Comment by juandent** [comment]
No I am not sure! Because I comment out all the use of Dynamic and Bond and I still get the message!!

What could it be? What does INM Stall mean? How can I debug it?

Thanks!!!
Juan Dent

**Comment by juandent** [comment]
Another question more on Bond's side for sure:

I need to create a dynamic property for the objectValueOfSelectedItem in a NSComboBox .. Have been trying to add an extension to NSComboBox like so.. the dynIndexOfSelectedItem seems to work fine but I am having trouble with the dynObjectValueOfSelectedItem: it says it cannot compile 
----------
class NSComboBoxDynamicHelper: NSObject {
    
    weak var control: NSComboBox?
    var listener: (Int -> Void)?
    
    init(control: NSComboBox) {
        self.control = control
        super.init()
        control.target = self
        control.action = Selector("selectionChanged:")
    }
    
    func selectionChanged(sender: AnyObject?) {
        if let combo : NSComboBox = sender as? NSComboBox {
            let index = combo.indexOfSelectedItem
            self.listener?(index)
        }
    }
}

class NSComboBoxDynamic<T>: InternalDynamic<Int> {
    
    let helper: NSComboBoxDynamicHelper
    
    init(control: NSComboBox) {
        self.helper = NSComboBoxDynamicHelper(control: control)
        super.init(control.indexOfSelectedItem )
        self.helper.listener =  { [unowned self] in self.value = $0 }
    }
}

class NSComboBoxDynamicT<T>: InternalDynamic<T> {
    
    let helper: NSComboBoxDynamicHelper
    
    init(control: NSComboBox) {
        self.helper = NSComboBoxDynamicHelper(control: control)
        super.init(nil )
        self.helper.listener =  { [unowned self] in self.value = $0 }
    }
}
 


private var indexOfSelectedItemDynamicHandleNSComboBox: UInt8 = 0;
private var objectValueOfSelectedItemDynamicHandleNSComboBox : UInt8 = 0;

extension NSComboBox: Dynamical, Bondable {
    
    public var dynIndexOfSelectedItem: Dynamic<Int> {
        
        if let d: AnyObject = objc_getAssociatedObject(self, &indexOfSelectedItemDynamicHandleNSComboBox) {
            return (d as? Dynamic<Int>)!
            
        } else {
            let d = NSComboBoxDynamic<Int>(control: self)
            let bond = Bond<Int>() { [weak self] v in if let s = self
                {
                    let itemCount = s.numberOfItems
                    if v > -1 && v < itemCount
                    {
                        s.selectItemAtIndex(v)
                    }
                }
            }
            d.bindTo(bond, fire: false, strongly: false)
            d.retain(bond)
            objc_setAssociatedObject(self, &indexOfSelectedItemDynamicHandleNSComboBox, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
            return d
        }
    }
    
    public var dynObjectValueOfSelectedItem : Dynamic<AnyObject?> {
        
        if let d: AnyObject = objc_getAssociatedObject(self, &objectValueOfSelectedItemDynamicHandleNSComboBox) {
            return (d as? Dynamic<AnyObject?>)!
            
        } else {
            let d = NSComboBoxDynamic<AnyObject?>(control: self)
            let bond = Bond<AnyObject?>() { [weak self] v in if let s = self
                {
                    s.objectValue = v
                }
            }
            d.bindTo(bond, fire: false, strongly: false)
            d.retain(bond)
            objc_setAssociatedObject(self, &objectValueOfSelectedItemDynamicHandleNSComboBox, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
            return d
        }
    }

}

public func <->> (left: NSComboBox, right: Dynamic<Int>) {
    left.dynIndexOfSelectedItem <->> right
}

public func <->> (left: Dynamic<Int>, right: NSComboBox) {
    left <->> right.dynIndexOfSelectedItem
}

----------



Thanks.,
Juan Dent

**Comment by juandent** [comment]
I also use a datasource for the combo so i cannot use the objectValueOfSelectedItem property
!!

**Comment by juandent** [comment]
I see that we have notifications for ComboBox -- maybe I should try to capture these?

**Comment by juandent** [comment]
How can I contribute to this amazing framework?

**Comment by juandent** [comment]
can I have some support if I contribute to this framework?

**Comment by srdanrasic** [comment]
@juandent, you're on good track, just mind your Types:

```swift
class NSComboBoxDynamicHelper: NSObject {
  
  weak var control: NSComboBox?
  var listener: (Int -> Void)?
  
  init(control: NSComboBox) {
    self.control = control
    super.init()
    control.target = self
    control.action = Selector("selectionChanged:")
  }
  
  func selectionChanged(sender: AnyObject?) {
    if let combo : NSComboBox = sender as? NSComboBox {
      let index = combo.indexOfSelectedItem
      self.listener?(index)
    }
  }
}

class NSComboBoxDynamicForIndex<T>: InternalDynamic<Int> {
  
  let helper: NSComboBoxDynamicHelper
  
  init(control: NSComboBox) {
    self.helper = NSComboBoxDynamicHelper(control: control)
    super.init(control.indexOfSelectedItem )
    self.helper.listener =  { [unowned self] in
      self.updatingFromSelf = true
      self.value = $0
      self.updatingFromSelf = false
    }
  }
}

class NSComboBoxDynamicForObject<T>: InternalDynamic<AnyObject?> {
  
  let helper: NSComboBoxDynamicHelper
  
  init(control: NSComboBox) {
    self.helper = NSComboBoxDynamicHelper(control: control)
    super.init(nil)
    self.helper.listener = { [unowned self, unowned control] in
      self.updatingFromSelf = true
      self.value = control.objectValues[$0]
      self.updatingFromSelf = false
    }
  }
}

private var indexOfSelectedItemDynamicHandleNSComboBox: UInt8 = 0;
private var objectValueOfSelectedItemDynamicHandleNSComboBox : UInt8 = 0;

extension NSComboBox: Dynamical, Bondable {
  
  public var dynIndexOfSelectedItem: Dynamic<Int> {
    
    if let d: AnyObject = objc_getAssociatedObject(self, &indexOfSelectedItemDynamicHandleNSComboBox) {
      return (d as? Dynamic<Int>)!
    } else {
      let d = NSComboBoxDynamicForIndex<Int>(control: self)
      let bond = Bond<Int>() { [weak self, weak d] v in
        if let s = self, d = d where !d.updatingFromSelf {  // prevents feedback loop
          let itemCount = s.numberOfItems
          if v > -1 && v < itemCount {
            s.selectItemAtIndex(v)
          }
        }
      }
      d.bindTo(bond, fire: false, strongly: false)
      d.retain(bond)
      objc_setAssociatedObject(self, &indexOfSelectedItemDynamicHandleNSComboBox, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
      return d
    }
  }
  
  public var dynObjectValueOfSelectedItem : Dynamic<AnyObject?> {
    
    if let d: AnyObject = objc_getAssociatedObject(self, &objectValueOfSelectedItemDynamicHandleNSComboBox) {
      return (d as? Dynamic<AnyObject?>)!
      
    } else {
      let d = NSComboBoxDynamicForObject<AnyObject?>(control: self)
      let bond = Bond<AnyObject?>() { [weak self, weak d] v in
        if let s = self, d = d where !d.updatingFromSelf {  // prevents feedback loop
          s.objectValue = v
        }
      }
      d.bindTo(bond, fire: false, strongly: false)
      d.retain(bond)
      objc_setAssociatedObject(self, &objectValueOfSelectedItemDynamicHandleNSComboBox, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
      return d
    }
  }
}

public func <->> (left: NSComboBox, right: Dynamic<Int>) {
  left.dynIndexOfSelectedItem <->> right
}

public func <->> (left: Dynamic<Int>, right: NSComboBox) {
  left <->> right.dynIndexOfSelectedItem
}
```
