### ISSUE TITLE
UITextField/UITextView's value doesn't reflect input text correctly

### ISSUE THREAD

**Issue by morizotter** [SwiftBond/Bond#64]
Unsettled converting text is set back to TextField/TextView so more texts are set than input. This is clear when inputting text which has unsettled converting state, for example, Japanese.

![before](https://cloud.githubusercontent.com/assets/536954/7730955/400cdf86-ff58-11e4-94f0-27baf6bdc740.gif)

**Comment by morizotter** [comment]
This issue is made by the discussion of https://github.com/SwiftBond/Bond/issues/61 .

**Comment by morizotter** [comment]
I'm not an expert of bidirectional binding. But I can explain the reason of the pull request https://github.com/SwiftBond/Bond/issues/61 from 2 points of view. First is conflict and second is the underlying cause. It's probably that the problem is not in Bond but UITextField/View's behavior.

## 1 The conflict

If Bond set the new value to the text field / view when user is editing it, it's conflict. This is the difficult issue that needs decision. But I think it's better to prioritize user's input. This pull request prioritize user's input. If the Bond value is different from user's input, prioritize Bond value. This is decision. When this pull request is merged, It is maybe good to write this behavior in README.

## 2 The underlying cause is the behavor of UITextField

I think the underlying cause is the behavor of UITextField/View. Try getting textField's text - which needs conversion, for example Japanese -  when `editingChanged(control: UITextField)` called and set it to the same instance of textField without using Bond. The result is pre-confirmed text and converting text. Bond or bidirectional binding is not the cause.

When `editingChanged(control: UITextField)` is called, the value of text field is not confirmed. Although setting the new value to text field, text field's unsettled value remains.

This strange behavior is probably only for UITextField/UITextView. So, you don't have to write if-clause every other binding item.

**Comment by srdanrasic** [comment]
You're right, there is an issue. Bond should not be overwriting text field/view value on each change.

**Comment by srdanrasic** [comment]
Hi @morizotter, please check out v3.7.2.

**Comment by morizotter** [comment]
@srdanrasic Thanks! It helps us a lot!

**Comment by srdanrasic** [comment]
You're welcome! And thanks again for reporting this.
