### ISSUE TITLE
UITableViewDataSourceBond should update in main thread

### ISSUE THREAD

**Issue by arytbk** [SwiftBond/Bond#69]
Currently UITableViewDataSourceBond is doing UITableView updates using the current thread where the Dynamic Array was updated. Since this is not always the main thread it will cause bugs and crashes.
Of course we could change the data model only using the main thread but it's a pain and it's not elegant. I think if would be much better to dispatch all UITableViewDataSourceBond UI updates to the main thread. (Same for collection views I guess!).

**Comment by srdanrasic** [comment]
Hi @arytbk, sorry for net getting earlier to this. If you're still facing this issues, try `deliver` method in v3.8.

For example:

```swift
deliver(repositories, on: dispatch_get_main_queue()).map { [unowned self] (repository: Repository) -> RepositoryTableViewCell in
    let cell = self.tableView.dequeueReusableCellWithIdentifier("cell") as RepositoryTableViewCell
    repository.name ->> cell.nameLabel
    repository.photo ->> cell.avatarImageView
    return cell
  } ->> tableViewDataSourceBond
```
