### ISSUE TITLE
"reduce" function semantics different to swift standard library and FRP

### ISSUE THREAD

**Issue by heiko-henrich** [SwiftBond/Bond#70]
Thank you for creating this marvelous library.
I like it very much for it's simplicity and clarity.
The current FRP libraries for swift (RxSwift and ReactiveCocoa 3.0)
are maybe more powerful but by far  not as consistent as SwiftBond, I think. (maybe because of backward compatibility reasons (to RAC 2.0 / reactive extensions)).

One little thing though that bothered me is the reduce function.
In other contexts (like the swift standard library, other functional languages  and FRP  APIs) it has different semantics:
e.g. in the swift standard library:
```swift
// Return the result of repeatedly calling 'combine' with an
// accumulated value initialized to 'initial' and each element of
// 'sequence', in turn.
func reduce<S : SequenceType, U>(sequence: S, initial: U, combine: @noescape (U, S.Generator.Element) -> U) -> U
```

On the other hand what you mean, the combination of different Dynamics to one, when one dynamic changes is expressed in Rx and RAC with combineLatest.

This is confusing I think.

I'd like to propose
1. a "real" reduce function which combines the value of the previous reduction with the new provided value, maybe to provide a Dynamic for an average value or a velocity computation from a sequence of screen coordinates.
```swift
func reduce<T, U>(dynamic: Dynamic<T>, initial: U, combine: T -> U) -> Dynamic<U>
```
A naming alternative would be "fold" or "foldl", but as the library is young, using "reduce" with the new meaning wouldn't hurt so much and would provide a consistency with the swift standard library.
2. to rename the original "reduce" function to "combine" or something like that

**Comment by srdanrasic** [comment]
Fixed in v4.
