### ISSUE TITLE
Question: Use of DynamicArray necessary?

### ISSUE THREAD

**Issue by Ben-G** [SwiftBond/Bond#72]
I just realized that I'm not using `DynamicArray` in my code base - instead I'm using a plain Swift `Array` like this:

`var exampleArray = Dynamic<[ExampleClass]>`

All of Bonds callbacks still work correctly; Whenever a Swift Array is modified, it is not modified in place but actually copied and reassigned. 

This works for operations that change the Array size, e.g.:

    exampleArray.append(ExampleClass())

As well as for changing elements at a specified index:

    exampleArray[0] = ExampleClass()

Given this, do we need to use `DynamicArray`?

**Comment by srdanrasic** [comment]
Hi @Ben-G,

You need DynamicArray only if you're interested in "fine-grained" changes - like what elements got inserted, deleted or updated. If you're only interested in a change of the array as whole, you don't need to use it.

https://github.com/SwiftBond/Bond#arrays-are-special-and-great

DynamicArray is also necessary when using table or collection view binding.

**Comment by Ben-G** [comment]
Thanks @srdanrasic for the quick response!

As Im trying to say, also "fine-grained" changes (as examples shown above) lead to a reassignment of Swift Arrays, therefor the Bond functionality works as expected for any modification of Swift Arrays.

Just trying to confirm that and make sure I'm not missing something :]

**Comment by srdanrasic** [comment]
Are you trying to say that this works?

```swift
var exampleArray = Dynamic<[ExampleClass]>([])
exampleArray.append(ExampleClass())
```

Hmm, that should not even compile because Dynamic has no method named `append`. Following will work, though:

```swift
var exampleArray = Dynamic<[ExampleClass]>([])
exampleArray.value.append(ExampleClass())
```

But binding that to an ArrayBond like this:

```swift
let myBond = ArrayBond<ExampleClass>()
exampleArray ->> myBond
```

Will not work properly because fine "fine-grained" changes will not be propagated. For example, `didInsertListener` listener

```swift
myBond.didInsertListener = { array, indices in
    println("Inserted objects at indices \(indices)")
}
```

will not be triggered...

**Comment by Ben-G** [comment]
Sorry; my example at the top was missing the access to `.value`.

I understand what you are saying now! If I'm interested in the details of a fine grained change I need to use `DynamicArray`.

However, even fine grained changes to regular Swift Arrays will trigger the regular listener - I just won't get detailed information about what has changed. 

Thanks for clarifying!

**Comment by srdanrasic** [comment]
I should probably have said "if you're interested in _observing_ "fine-grained" changes"... Anyway, glad it helps :)
