### ISSUE TITLE
Swift 2.0 and Xcode 7 support

### ISSUE THREAD

**Issue by sync** [SwiftBond/Bond#73]
- Initial Swift 2.0 support
https://github.com/sync/Bond/commits/feature/swift-2.0

- having fun with some code crashing the compiler, something to do with ABI compatibility
https://github.com/sync/Bond/commit/c66c131a3d6e1a35bbfb0e74d646d2c3d8a3cda5

**Comment by toineheuvelmans** [comment]
With Xcode 7.0 beta 3 and today's (July 10th) version of Bond swift-2.0 branch I get a compile error in Bond+Foundation.swift:50 :
`override dynamic func observeValueForKeyPath(...)`
"Method does not override any method from its superclass". Any idea?

**Comment by sync** [comment]
See https://github.com/SwiftBond/Bond/pull/97

**Comment by gvimlan95** [comment]
Adding this framework(by copy and pasting all the swift files) to my existing framework running on Xcode 7 beta 4 gives error on the bond swift files.Anyway I can solve this?

thank you

**Comment by srdanrasic** [comment]
@gvimlan95, there is no official Swift 2.0 support yet. Bond v4 will be Swift 2.0 ready. You can checkout  `bond-4` branch, but it might now be fully stable yet. Also, some things have changes, so the documentation is out of the date.

**Comment by srdanrasic** [comment]
Bond 4 is Swift 2 ready.
