### ISSUE TITLE
No such module 'Bond'

### ISSUE THREAD

**Issue by jjfeiler** [SwiftBond/Bond#79]
Using carthage, Cartfile as follows:
github "SwiftBond/Bond" ~> 3.7
carthage update runs fine, added framework to project as directed on carthage page, I get the error 

/Users/jjfeiler/Workspace/Personal/GeoTour/GeoTour/FirstViewController.swift:13:8: No such module 'Bond'

that line is 

import Bond

**Comment by morizotter** [comment]
I can use Carthage.

`github "SwiftBond/Bond" == 3.7.4`
