### ISSUE TITLE
Using Bond and @NSMananged CoreData

### ISSUE THREAD

**Issue by binottoeduardo** [SwiftBond/Bond#80]
Hi, I'm trying using Bond but don't make UITextField and @NSMananged var name : String.

Ex: 

class User: NSManagedObject {

    @NSManaged var name: String
    @NSManaged var password: String

}

import UIKit
import Bond

class TestVC:  UIViewController {  
    @IBOutlet weak var name: UITextField!
    @IBOutlet weak var password: UITextField!

    var user = User()
    override func viewDidLoad() {
        super.viewDidLoad()
    
        // have problem
        name<->> user.name
        password<->> user.password
}

how I using Bond and NSManagedObject in my project ?
I'm very happy your framework.

sorry with my english.

**Comment by ivanmoskalev** [comment]
Hi! Did you try to use [Two way Key-Value-Observing](https://github.com/SwiftBond/Bond#two-way-key-value-observing)?

**Comment by ivanmoskalev** [comment]
@srdanrasic I suggest we make a tag on Stackgoverflow for questions, what do you think? Typhoon does that.

**Comment by srdanrasic** [comment]
@ivanmoskalev, how do we do that? :)

**Comment by ivanmoskalev** [comment]
Just ask people to use it in Readme :)
