### ISSUE TITLE
Add distinct() operator

### ISSUE THREAD

**Issue by ivanmoskalev** [SwiftBond/Bond#83]
Sometimes it is useful to filter out consecutive duplicates from the stream of values. I don't see any immediate need for an implementation that filters out all values throughout the history though.

I can take on this improvement in a couple of days! Please assign this task to me if you decide that we do it :)

**Comment by tonyarnold** [comment]
This would be great. I could use this if you implemented it.

**Comment by srdanrasic** [comment]
@ivanmoskalev, that would be great. I guess it would work only with types conforming to Equatable?

**Comment by ivanmoskalev** [comment]
Yes, exactly!

**Comment by ivanmoskalev** [comment]
Closed, PR merged in
