### ISSUE TITLE
Method of injecting side effects before/after a binding fires

### ISSUE THREAD

**Issue by tonyarnold** [SwiftBond/Bond#84]
It would be nice to be able to inject side effects before/after a binding commits a change. My use case here is making things animate — if I set the colour on an NSColorWell, it snaps into place, but if I could inject a call to `NSAnimationContext` before the colour is set I could smoothly fade between colours. 

I can directly change the Bond extension for this class, but it does seem like some kind of `then` like functionality might fit here.

**Comment by srdanrasic** [comment]
That could be very powerful feature. We could easily extend Dynamic with a new function that would allow us to manually commit change while doing side effects.

```swift
extension Dynamic {
  public func intercept(closure: (Void -> Void) -> Void) -> Dynamic<T>
}
```

User would provide a closure to perform side effects. The closure would receive another closure as an argument that would be used to propagate changes.

```swift
@IBOutlet weak var label: UILabel!
let alpha = Dynamic<CGFloat>(0)

alpha.intercept { commit in
  // perform some action before change
  commit() // propagate change
  // perform some action after change
} ->> label.dynAlpha
```

So, to animate change of alpha we could do:

```swift
alpha.intercept { commit in
  UIView.animateWithDuration(0.25){ 
    commit()
  }
} ->> label.dynAlpha
```

I'm also thinking of a bit more powerful variant where user would also get a new value which he has to commit, potentially changing it. Like a real man in the middle attack on our binding. 

```swift
extension Dynamic {
  public func intercept(closure: (T -> Void, T) -> Void) -> Dynamic<T>
}
```

```swift
alpha.intercept { commit, value in
  UIView.animateWithDuration(0.25){ 
    commit(value)
  }
} ->> label.dynAlpha
```

Would something like that work for you? Also, do you have any better name suggestion for such function?

**Comment by tonyarnold** [comment]
That looks pretty close to what I want. The only thing I'm missing now is some method to coalesce disparate changes across multiple controls and properties (although I'm not sure how that would look API-wise).

Thanks @srdanrasic :)

**Comment by ivanmoskalev** [comment]
Awesome @srdanrasic!

I just thought: maybe it would be appropriate to name this operator `decorate`? Not only does it extend the particular `Dynamic`'s behaviour ('decorating' it), but it is also intended for adding animations and other visual adornments – decorations :)

**Comment by srdanrasic** [comment]
I don't think this can be applied to v4. Method `observe` can be used to achieve something like that.
