### ISSUE TITLE
cannot be applied to operands of type 'String' and 'Dynamic<String>'

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [SwiftBond/Bond#96]
sceneModel.req.password <->>  loginView.passwordTextField.dynText    

error :Binary operator '<->>' cannot be applied to operands of type 'String' and 'Dynamic<String>'

**Comment by murrayds** [comment]
It sounds like your variable "sceneModel.req.password" is of type String and not of type Dynamic<String>.

Try instantiating the password variable like this: 

```
var password: Dynamic<String> = Dynamic("default")
```

and accessing the value like this:
```
let value = sceneModel.req.password.value
```

Bonds can only be made between two dynamic variables or between a dynamic variable and a bond.

**Comment by srdanrasic** [comment]
@Darkhorse-Fraternity Unfortunately Bond does not work like that. It would be great, though :)

@murrayds is right. You might also take a look at KVO: https://github.com/SwiftBond/Bond#key-value-observing
