### ISSUE TITLE
Cleaning up Dynamic Variable Implementation 

### ISSUE THREAD

**Issue by murrayds** [SwiftBond/Bond#99]
thanks @ivanmoskalev for recommending the change in a branch commit I made.

Throughout the project, dynamic variables in the view extensions are implemented in the following way 
```
public var dynHidden: Dynamic<Bool> {
    if let d: AnyObject = objc_getAssociatedObject(self, &hiddenDynamicHandleUIView) {
      return (d as? Dynamic<Bool>)!
    } else {
      let d = InternalDynamic<Bool>(self.hidden)
      let bond = Bond<Bool>() { [weak self] v in if let s = self { s.hidden = v } }
      d.bindTo(bond, fire: false, strongly: false)
      d.retain(bond)
      objc_setAssociatedObject(self, &hiddenDynamicHandleUIView, d, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN_NONATOMIC))
      return d
    }
  }
```

This issue focuses on the following line of the above snippet
```
let bond = Bond<Bool>() { [weak self] v in if let s = self { s.hidden = v } }
```

After a short discussion on the topic, it was concluded that a slightly cleaner (and more swift-like) way of implementing the snippet would be the following:
```
let bond = Bond<Bool>() { [weak self] v in let s?.hidden = v }
```

or, perhaps in even less code (but possibly poorer readability), the variables could be implemented as such
```
let bond = Bond<Bool>() { [weak self] in s?.hidden = $0  }
```

this is obviously a low priority issue but could serve as an easy modification for someone newer to the project (such as myself). Some input on preferred style would be appreciated (original style, cleaner code with a defined closure variable, or a more functional implementation using $0)

**Comment by ivanmoskalev** [comment]
Awesome! :+1:  
I personally like the shorthand-arg way of doing it.

**Comment by srdanrasic** [comment]
Agreed, that would be much nicer. Those things are from the times when Xcode was so unstable that you had to make everything explicit or you'd end up with SourceKit crashes.

**Comment by murrayds** [comment]
Awesome. I also personally like the shorthand no-arg way of doing it, Unless there are any objections I might soon start working on the necessary changes.

**Comment by murrayds** [comment]
I have been making some changes to the code as per the decisions made in this issue however I noticed a few interesting details while searching through the code.

In some parts of the project, in particular the UITableView and UICollectionView extensions under their respective declarations of their data source bonds. 

```
self.didInsertListener = { [weak self] array, i in
      if let s = self {
        if let tableView: UITableView = self?.tableView {
          perform(animated: !disableAnimation) {
            tableView.beginUpdates()
            tableView.insertSections(NSIndexSet(array: i), withRowAnimation: UITableViewRowAnimation.Automatic)
            
            for section in sorted(i, <) {
              let sectionBond = UITableViewDataSourceSectionBond<Void>(tableView: tableView, section: section, disableAnimation: disableAnimation)
              let sectionDynamic = array[section]
              sectionDynamic.bindTo(sectionBond)
              s.sectionBonds.insert(sectionBond, atIndex: section)
              
              for var idx = section + 1; idx < s.sectionBonds.count; idx++ {
                s.sectionBonds[idx].section += 1
              }
            }
            
            tableView.endUpdates()
          }
        }
      }
    }
```

If you look at the above snippet, you should notice that the variable 's' stored self and is explicitly defined in the top if let... statement. The 's' variable is then referenced several times in the following block. The question is: should the 's' variable continue to be used? or should the upper-most if let... statement be removed and instead replace 's' with 'self?' in the code block?

**Comment by srdanrasic** [comment]
Hi @murrayds. I think that `s` in this case should be left in order to maintain atomicity of the operation.
